version: "3.8"

services:
  shinoa:
    image: node:14-alpine
    command: /bin/sh -c "yarn && yarn dev"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_OPTIONS: "--unhandled-rejections=throw"
      TOKEN: ~
      LOG_LEVEL: debug
