version: "3.8"

services:
  shinoa:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/shinoa
      TOKEN: ~
      LOG_LEVEL: ~
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shinoa
