version: "3.8"

services:
  shinoa:
    image: hayd/alpine-deno:1.9.0
    command: run -A --watch --unstable src/main.ts
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      TOKEN: ~
      LOG_LEVEL: DEBUG
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shinoa
