apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinoa-deployment
  labels:
    app: shinoa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shinoa
  template:
    metadata:
      labels:
        app: shinoa
    spec:
      containers:
        - name: shinoa
          image: omegavesko/shinoa:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db
                  key: database_url
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: token
                  key: token
            - name: SAUCENAO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: saucenao
                  key: api-key
            - name: WEEB_SH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weeb
                  key: key
            - name: LOG_LEVEL
              value: debug
            - name: SENTRY_DSN
              value: https://a16130edcd654fe2a89fe58ab5315a6f@o345514.ingest.sentry.io/5991672
