
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"
export type * from '../models.ts'
export type * from './prismaNamespace.ts'
export const Decimal = runtime.Decimal
export const ModelName = {
  KeyValueItem: 'KeyValueItem',
  Quote: 'Quote',
  Sticker: 'Sticker',
  Mute: 'Mute',
  Poll: 'Poll',
  Vote: 'Vote',
  StarboardItem: 'StarboardItem',
  Club: 'Club',
  ClubVote: 'ClubVote'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/**
 * Enums
 */
export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const KeyValueItemScalarFieldEnum = {
  key: 'key',
  value: 'value'
} as const

export type KeyValueItemScalarFieldEnum = (typeof KeyValueItemScalarFieldEnum)[keyof typeof KeyValueItemScalarFieldEnum]


export const QuoteScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  userId: 'userId',
  messageId: 'messageId',
  message: 'message'
} as const

export type QuoteScalarFieldEnum = (typeof QuoteScalarFieldEnum)[keyof typeof QuoteScalarFieldEnum]


export const StickerScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  tag: 'tag',
  url: 'url'
} as const

export type StickerScalarFieldEnum = (typeof StickerScalarFieldEnum)[keyof typeof StickerScalarFieldEnum]


export const MuteScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  memberId: 'memberId',
  endsAt: 'endsAt'
} as const

export type MuteScalarFieldEnum = (typeof MuteScalarFieldEnum)[keyof typeof MuteScalarFieldEnum]


export const PollScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  localId: 'localId',
  name: 'name',
  channelId: 'channelId',
  messsageId: 'messsageId',
  active: 'active',
  options: 'options',
  minValues: 'minValues',
  maxValues: 'maxValues',
  allowChangingVote: 'allowChangingVote',
  showResults: 'showResults'
} as const

export type PollScalarFieldEnum = (typeof PollScalarFieldEnum)[keyof typeof PollScalarFieldEnum]


export const VoteScalarFieldEnum = {
  id: 'id',
  pollId: 'pollId',
  userId: 'userId',
  values: 'values'
} as const

export type VoteScalarFieldEnum = (typeof VoteScalarFieldEnum)[keyof typeof VoteScalarFieldEnum]


export const StarboardItemScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  messageId: 'messageId',
  starboardMessageId: 'starboardMessageId'
} as const

export type StarboardItemScalarFieldEnum = (typeof StarboardItemScalarFieldEnum)[keyof typeof StarboardItemScalarFieldEnum]


export const ClubScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  channelId: 'channelId',
  archived: 'archived'
} as const

export type ClubScalarFieldEnum = (typeof ClubScalarFieldEnum)[keyof typeof ClubScalarFieldEnum]


export const ClubVoteScalarFieldEnum = {
  id: 'id',
  guildId: 'guildId',
  channelId: 'channelId',
  messageId: 'messageId',
  clubName: 'clubName',
  votesRequired: 'votesRequired'
} as const

export type ClubVoteScalarFieldEnum = (typeof ClubVoteScalarFieldEnum)[keyof typeof ClubVoteScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

