
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model KeyValueItem
 * 
 */
export type KeyValueItem = Prisma.KeyValueItemModel
/**
 * Model Quote
 * 
 */
export type Quote = Prisma.QuoteModel
/**
 * Model Sticker
 * 
 */
export type Sticker = Prisma.StickerModel
/**
 * Model Mute
 * 
 */
export type Mute = Prisma.MuteModel
/**
 * Model Poll
 * 
 */
export type Poll = Prisma.PollModel
/**
 * Model Vote
 * 
 */
export type Vote = Prisma.VoteModel
/**
 * Model StarboardItem
 * 
 */
export type StarboardItem = Prisma.StarboardItemModel
/**
 * Model Club
 * 
 */
export type Club = Prisma.ClubModel
/**
 * Model ClubVote
 * 
 */
export type ClubVote = Prisma.ClubVoteModel
