
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `ClubVote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ClubVote
 * 
 */
export type ClubVoteModel = runtime.Types.Result.DefaultSelection<Prisma.$ClubVotePayload>

export type AggregateClubVote = {
  _count: ClubVoteCountAggregateOutputType | null
  _avg: ClubVoteAvgAggregateOutputType | null
  _sum: ClubVoteSumAggregateOutputType | null
  _min: ClubVoteMinAggregateOutputType | null
  _max: ClubVoteMaxAggregateOutputType | null
}

export type ClubVoteAvgAggregateOutputType = {
  id: number | null
  votesRequired: number | null
}

export type ClubVoteSumAggregateOutputType = {
  id: number | null
  votesRequired: number | null
}

export type ClubVoteMinAggregateOutputType = {
  id: number | null
  guildId: string | null
  channelId: string | null
  messageId: string | null
  clubName: string | null
  votesRequired: number | null
}

export type ClubVoteMaxAggregateOutputType = {
  id: number | null
  guildId: string | null
  channelId: string | null
  messageId: string | null
  clubName: string | null
  votesRequired: number | null
}

export type ClubVoteCountAggregateOutputType = {
  id: number
  guildId: number
  channelId: number
  messageId: number
  clubName: number
  votesRequired: number
  _all: number
}


export type ClubVoteAvgAggregateInputType = {
  id?: true
  votesRequired?: true
}

export type ClubVoteSumAggregateInputType = {
  id?: true
  votesRequired?: true
}

export type ClubVoteMinAggregateInputType = {
  id?: true
  guildId?: true
  channelId?: true
  messageId?: true
  clubName?: true
  votesRequired?: true
}

export type ClubVoteMaxAggregateInputType = {
  id?: true
  guildId?: true
  channelId?: true
  messageId?: true
  clubName?: true
  votesRequired?: true
}

export type ClubVoteCountAggregateInputType = {
  id?: true
  guildId?: true
  channelId?: true
  messageId?: true
  clubName?: true
  votesRequired?: true
  _all?: true
}

export type ClubVoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClubVote to aggregate.
   */
  where?: Prisma.ClubVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClubVotes to fetch.
   */
  orderBy?: Prisma.ClubVoteOrderByWithRelationInput | Prisma.ClubVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClubVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClubVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClubVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ClubVotes
  **/
  _count?: true | ClubVoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ClubVoteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ClubVoteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClubVoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClubVoteMaxAggregateInputType
}

export type GetClubVoteAggregateType<T extends ClubVoteAggregateArgs> = {
      [P in keyof T & keyof AggregateClubVote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClubVote[P]>
    : Prisma.GetScalarType<T[P], AggregateClubVote[P]>
}




export type ClubVoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClubVoteWhereInput
  orderBy?: Prisma.ClubVoteOrderByWithAggregationInput | Prisma.ClubVoteOrderByWithAggregationInput[]
  by: Prisma.ClubVoteScalarFieldEnum[] | Prisma.ClubVoteScalarFieldEnum
  having?: Prisma.ClubVoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClubVoteCountAggregateInputType | true
  _avg?: ClubVoteAvgAggregateInputType
  _sum?: ClubVoteSumAggregateInputType
  _min?: ClubVoteMinAggregateInputType
  _max?: ClubVoteMaxAggregateInputType
}

export type ClubVoteGroupByOutputType = {
  id: number
  guildId: string
  channelId: string
  messageId: string
  clubName: string
  votesRequired: number | null
  _count: ClubVoteCountAggregateOutputType | null
  _avg: ClubVoteAvgAggregateOutputType | null
  _sum: ClubVoteSumAggregateOutputType | null
  _min: ClubVoteMinAggregateOutputType | null
  _max: ClubVoteMaxAggregateOutputType | null
}

type GetClubVoteGroupByPayload<T extends ClubVoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClubVoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClubVoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClubVoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClubVoteGroupByOutputType[P]>
      }
    >
  >



export type ClubVoteWhereInput = {
  AND?: Prisma.ClubVoteWhereInput | Prisma.ClubVoteWhereInput[]
  OR?: Prisma.ClubVoteWhereInput[]
  NOT?: Prisma.ClubVoteWhereInput | Prisma.ClubVoteWhereInput[]
  id?: Prisma.IntFilter<"ClubVote"> | number
  guildId?: Prisma.StringFilter<"ClubVote"> | string
  channelId?: Prisma.StringFilter<"ClubVote"> | string
  messageId?: Prisma.StringFilter<"ClubVote"> | string
  clubName?: Prisma.StringFilter<"ClubVote"> | string
  votesRequired?: Prisma.IntNullableFilter<"ClubVote"> | number | null
}

export type ClubVoteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  clubName?: Prisma.SortOrder
  votesRequired?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type ClubVoteWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ClubVoteWhereInput | Prisma.ClubVoteWhereInput[]
  OR?: Prisma.ClubVoteWhereInput[]
  NOT?: Prisma.ClubVoteWhereInput | Prisma.ClubVoteWhereInput[]
  guildId?: Prisma.StringFilter<"ClubVote"> | string
  channelId?: Prisma.StringFilter<"ClubVote"> | string
  messageId?: Prisma.StringFilter<"ClubVote"> | string
  clubName?: Prisma.StringFilter<"ClubVote"> | string
  votesRequired?: Prisma.IntNullableFilter<"ClubVote"> | number | null
}, "id">

export type ClubVoteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  clubName?: Prisma.SortOrder
  votesRequired?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ClubVoteCountOrderByAggregateInput
  _avg?: Prisma.ClubVoteAvgOrderByAggregateInput
  _max?: Prisma.ClubVoteMaxOrderByAggregateInput
  _min?: Prisma.ClubVoteMinOrderByAggregateInput
  _sum?: Prisma.ClubVoteSumOrderByAggregateInput
}

export type ClubVoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClubVoteScalarWhereWithAggregatesInput | Prisma.ClubVoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClubVoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClubVoteScalarWhereWithAggregatesInput | Prisma.ClubVoteScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ClubVote"> | number
  guildId?: Prisma.StringWithAggregatesFilter<"ClubVote"> | string
  channelId?: Prisma.StringWithAggregatesFilter<"ClubVote"> | string
  messageId?: Prisma.StringWithAggregatesFilter<"ClubVote"> | string
  clubName?: Prisma.StringWithAggregatesFilter<"ClubVote"> | string
  votesRequired?: Prisma.IntNullableWithAggregatesFilter<"ClubVote"> | number | null
}

export type ClubVoteCreateInput = {
  guildId: string
  channelId: string
  messageId: string
  clubName: string
  votesRequired?: number | null
}

export type ClubVoteUncheckedCreateInput = {
  id?: number
  guildId: string
  channelId: string
  messageId: string
  clubName: string
  votesRequired?: number | null
}

export type ClubVoteUpdateInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  clubName?: Prisma.StringFieldUpdateOperationsInput | string
  votesRequired?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ClubVoteUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  clubName?: Prisma.StringFieldUpdateOperationsInput | string
  votesRequired?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ClubVoteCreateManyInput = {
  id?: number
  guildId: string
  channelId: string
  messageId: string
  clubName: string
  votesRequired?: number | null
}

export type ClubVoteUpdateManyMutationInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  clubName?: Prisma.StringFieldUpdateOperationsInput | string
  votesRequired?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ClubVoteUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  clubName?: Prisma.StringFieldUpdateOperationsInput | string
  votesRequired?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ClubVoteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  clubName?: Prisma.SortOrder
  votesRequired?: Prisma.SortOrder
}

export type ClubVoteAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  votesRequired?: Prisma.SortOrder
}

export type ClubVoteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  clubName?: Prisma.SortOrder
  votesRequired?: Prisma.SortOrder
}

export type ClubVoteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  clubName?: Prisma.SortOrder
  votesRequired?: Prisma.SortOrder
}

export type ClubVoteSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  votesRequired?: Prisma.SortOrder
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type ClubVoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  channelId?: boolean
  messageId?: boolean
  clubName?: boolean
  votesRequired?: boolean
}, ExtArgs["result"]["clubVote"]>

export type ClubVoteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  channelId?: boolean
  messageId?: boolean
  clubName?: boolean
  votesRequired?: boolean
}, ExtArgs["result"]["clubVote"]>

export type ClubVoteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  channelId?: boolean
  messageId?: boolean
  clubName?: boolean
  votesRequired?: boolean
}, ExtArgs["result"]["clubVote"]>

export type ClubVoteSelectScalar = {
  id?: boolean
  guildId?: boolean
  channelId?: boolean
  messageId?: boolean
  clubName?: boolean
  votesRequired?: boolean
}

export type ClubVoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "guildId" | "channelId" | "messageId" | "clubName" | "votesRequired", ExtArgs["result"]["clubVote"]>

export type $ClubVotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ClubVote"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    guildId: string
    channelId: string
    messageId: string
    clubName: string
    votesRequired: number | null
  }, ExtArgs["result"]["clubVote"]>
  composites: {}
}

export type ClubVoteGetPayload<S extends boolean | null | undefined | ClubVoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ClubVotePayload, S>

export type ClubVoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClubVoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ClubVoteCountAggregateInputType | true
  }

export interface ClubVoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ClubVote'], meta: { name: 'ClubVote' } }
  /**
   * Find zero or one ClubVote that matches the filter.
   * @param {ClubVoteFindUniqueArgs} args - Arguments to find a ClubVote
   * @example
   * // Get one ClubVote
   * const clubVote = await prisma.clubVote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClubVoteFindUniqueArgs>(args: Prisma.SelectSubset<T, ClubVoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClubVoteClient<runtime.Types.Result.GetResult<Prisma.$ClubVotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ClubVote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClubVoteFindUniqueOrThrowArgs} args - Arguments to find a ClubVote
   * @example
   * // Get one ClubVote
   * const clubVote = await prisma.clubVote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClubVoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClubVoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClubVoteClient<runtime.Types.Result.GetResult<Prisma.$ClubVotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClubVote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubVoteFindFirstArgs} args - Arguments to find a ClubVote
   * @example
   * // Get one ClubVote
   * const clubVote = await prisma.clubVote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClubVoteFindFirstArgs>(args?: Prisma.SelectSubset<T, ClubVoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClubVoteClient<runtime.Types.Result.GetResult<Prisma.$ClubVotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClubVote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubVoteFindFirstOrThrowArgs} args - Arguments to find a ClubVote
   * @example
   * // Get one ClubVote
   * const clubVote = await prisma.clubVote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClubVoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClubVoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClubVoteClient<runtime.Types.Result.GetResult<Prisma.$ClubVotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ClubVotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubVoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ClubVotes
   * const clubVotes = await prisma.clubVote.findMany()
   * 
   * // Get first 10 ClubVotes
   * const clubVotes = await prisma.clubVote.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const clubVoteWithIdOnly = await prisma.clubVote.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ClubVoteFindManyArgs>(args?: Prisma.SelectSubset<T, ClubVoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClubVotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ClubVote.
   * @param {ClubVoteCreateArgs} args - Arguments to create a ClubVote.
   * @example
   * // Create one ClubVote
   * const ClubVote = await prisma.clubVote.create({
   *   data: {
   *     // ... data to create a ClubVote
   *   }
   * })
   * 
   */
  create<T extends ClubVoteCreateArgs>(args: Prisma.SelectSubset<T, ClubVoteCreateArgs<ExtArgs>>): Prisma.Prisma__ClubVoteClient<runtime.Types.Result.GetResult<Prisma.$ClubVotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ClubVotes.
   * @param {ClubVoteCreateManyArgs} args - Arguments to create many ClubVotes.
   * @example
   * // Create many ClubVotes
   * const clubVote = await prisma.clubVote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClubVoteCreateManyArgs>(args?: Prisma.SelectSubset<T, ClubVoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ClubVotes and returns the data saved in the database.
   * @param {ClubVoteCreateManyAndReturnArgs} args - Arguments to create many ClubVotes.
   * @example
   * // Create many ClubVotes
   * const clubVote = await prisma.clubVote.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ClubVotes and only return the `id`
   * const clubVoteWithIdOnly = await prisma.clubVote.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ClubVoteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ClubVoteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClubVotePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ClubVote.
   * @param {ClubVoteDeleteArgs} args - Arguments to delete one ClubVote.
   * @example
   * // Delete one ClubVote
   * const ClubVote = await prisma.clubVote.delete({
   *   where: {
   *     // ... filter to delete one ClubVote
   *   }
   * })
   * 
   */
  delete<T extends ClubVoteDeleteArgs>(args: Prisma.SelectSubset<T, ClubVoteDeleteArgs<ExtArgs>>): Prisma.Prisma__ClubVoteClient<runtime.Types.Result.GetResult<Prisma.$ClubVotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ClubVote.
   * @param {ClubVoteUpdateArgs} args - Arguments to update one ClubVote.
   * @example
   * // Update one ClubVote
   * const clubVote = await prisma.clubVote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClubVoteUpdateArgs>(args: Prisma.SelectSubset<T, ClubVoteUpdateArgs<ExtArgs>>): Prisma.Prisma__ClubVoteClient<runtime.Types.Result.GetResult<Prisma.$ClubVotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ClubVotes.
   * @param {ClubVoteDeleteManyArgs} args - Arguments to filter ClubVotes to delete.
   * @example
   * // Delete a few ClubVotes
   * const { count } = await prisma.clubVote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClubVoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClubVoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClubVotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubVoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ClubVotes
   * const clubVote = await prisma.clubVote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClubVoteUpdateManyArgs>(args: Prisma.SelectSubset<T, ClubVoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClubVotes and returns the data updated in the database.
   * @param {ClubVoteUpdateManyAndReturnArgs} args - Arguments to update many ClubVotes.
   * @example
   * // Update many ClubVotes
   * const clubVote = await prisma.clubVote.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ClubVotes and only return the `id`
   * const clubVoteWithIdOnly = await prisma.clubVote.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ClubVoteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ClubVoteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClubVotePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ClubVote.
   * @param {ClubVoteUpsertArgs} args - Arguments to update or create a ClubVote.
   * @example
   * // Update or create a ClubVote
   * const clubVote = await prisma.clubVote.upsert({
   *   create: {
   *     // ... data to create a ClubVote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ClubVote we want to update
   *   }
   * })
   */
  upsert<T extends ClubVoteUpsertArgs>(args: Prisma.SelectSubset<T, ClubVoteUpsertArgs<ExtArgs>>): Prisma.Prisma__ClubVoteClient<runtime.Types.Result.GetResult<Prisma.$ClubVotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ClubVotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubVoteCountArgs} args - Arguments to filter ClubVotes to count.
   * @example
   * // Count the number of ClubVotes
   * const count = await prisma.clubVote.count({
   *   where: {
   *     // ... the filter for the ClubVotes we want to count
   *   }
   * })
  **/
  count<T extends ClubVoteCountArgs>(
    args?: Prisma.Subset<T, ClubVoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClubVoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ClubVote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubVoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClubVoteAggregateArgs>(args: Prisma.Subset<T, ClubVoteAggregateArgs>): Prisma.PrismaPromise<GetClubVoteAggregateType<T>>

  /**
   * Group by ClubVote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubVoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClubVoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClubVoteGroupByArgs['orderBy'] }
      : { orderBy?: ClubVoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClubVoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClubVoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ClubVote model
 */
readonly fields: ClubVoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ClubVote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClubVoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ClubVote model
 */
export interface ClubVoteFieldRefs {
  readonly id: Prisma.FieldRef<"ClubVote", 'Int'>
  readonly guildId: Prisma.FieldRef<"ClubVote", 'String'>
  readonly channelId: Prisma.FieldRef<"ClubVote", 'String'>
  readonly messageId: Prisma.FieldRef<"ClubVote", 'String'>
  readonly clubName: Prisma.FieldRef<"ClubVote", 'String'>
  readonly votesRequired: Prisma.FieldRef<"ClubVote", 'Int'>
}
    

// Custom InputTypes
/**
 * ClubVote findUnique
 */
export type ClubVoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubVote
   */
  select?: Prisma.ClubVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClubVote
   */
  omit?: Prisma.ClubVoteOmit<ExtArgs> | null
  /**
   * Filter, which ClubVote to fetch.
   */
  where: Prisma.ClubVoteWhereUniqueInput
}

/**
 * ClubVote findUniqueOrThrow
 */
export type ClubVoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubVote
   */
  select?: Prisma.ClubVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClubVote
   */
  omit?: Prisma.ClubVoteOmit<ExtArgs> | null
  /**
   * Filter, which ClubVote to fetch.
   */
  where: Prisma.ClubVoteWhereUniqueInput
}

/**
 * ClubVote findFirst
 */
export type ClubVoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubVote
   */
  select?: Prisma.ClubVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClubVote
   */
  omit?: Prisma.ClubVoteOmit<ExtArgs> | null
  /**
   * Filter, which ClubVote to fetch.
   */
  where?: Prisma.ClubVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClubVotes to fetch.
   */
  orderBy?: Prisma.ClubVoteOrderByWithRelationInput | Prisma.ClubVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClubVotes.
   */
  cursor?: Prisma.ClubVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClubVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClubVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClubVotes.
   */
  distinct?: Prisma.ClubVoteScalarFieldEnum | Prisma.ClubVoteScalarFieldEnum[]
}

/**
 * ClubVote findFirstOrThrow
 */
export type ClubVoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubVote
   */
  select?: Prisma.ClubVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClubVote
   */
  omit?: Prisma.ClubVoteOmit<ExtArgs> | null
  /**
   * Filter, which ClubVote to fetch.
   */
  where?: Prisma.ClubVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClubVotes to fetch.
   */
  orderBy?: Prisma.ClubVoteOrderByWithRelationInput | Prisma.ClubVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClubVotes.
   */
  cursor?: Prisma.ClubVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClubVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClubVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClubVotes.
   */
  distinct?: Prisma.ClubVoteScalarFieldEnum | Prisma.ClubVoteScalarFieldEnum[]
}

/**
 * ClubVote findMany
 */
export type ClubVoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubVote
   */
  select?: Prisma.ClubVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClubVote
   */
  omit?: Prisma.ClubVoteOmit<ExtArgs> | null
  /**
   * Filter, which ClubVotes to fetch.
   */
  where?: Prisma.ClubVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClubVotes to fetch.
   */
  orderBy?: Prisma.ClubVoteOrderByWithRelationInput | Prisma.ClubVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ClubVotes.
   */
  cursor?: Prisma.ClubVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClubVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClubVotes.
   */
  skip?: number
  distinct?: Prisma.ClubVoteScalarFieldEnum | Prisma.ClubVoteScalarFieldEnum[]
}

/**
 * ClubVote create
 */
export type ClubVoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubVote
   */
  select?: Prisma.ClubVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClubVote
   */
  omit?: Prisma.ClubVoteOmit<ExtArgs> | null
  /**
   * The data needed to create a ClubVote.
   */
  data: Prisma.XOR<Prisma.ClubVoteCreateInput, Prisma.ClubVoteUncheckedCreateInput>
}

/**
 * ClubVote createMany
 */
export type ClubVoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ClubVotes.
   */
  data: Prisma.ClubVoteCreateManyInput | Prisma.ClubVoteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ClubVote createManyAndReturn
 */
export type ClubVoteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubVote
   */
  select?: Prisma.ClubVoteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ClubVote
   */
  omit?: Prisma.ClubVoteOmit<ExtArgs> | null
  /**
   * The data used to create many ClubVotes.
   */
  data: Prisma.ClubVoteCreateManyInput | Prisma.ClubVoteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ClubVote update
 */
export type ClubVoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubVote
   */
  select?: Prisma.ClubVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClubVote
   */
  omit?: Prisma.ClubVoteOmit<ExtArgs> | null
  /**
   * The data needed to update a ClubVote.
   */
  data: Prisma.XOR<Prisma.ClubVoteUpdateInput, Prisma.ClubVoteUncheckedUpdateInput>
  /**
   * Choose, which ClubVote to update.
   */
  where: Prisma.ClubVoteWhereUniqueInput
}

/**
 * ClubVote updateMany
 */
export type ClubVoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ClubVotes.
   */
  data: Prisma.XOR<Prisma.ClubVoteUpdateManyMutationInput, Prisma.ClubVoteUncheckedUpdateManyInput>
  /**
   * Filter which ClubVotes to update
   */
  where?: Prisma.ClubVoteWhereInput
  /**
   * Limit how many ClubVotes to update.
   */
  limit?: number
}

/**
 * ClubVote updateManyAndReturn
 */
export type ClubVoteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubVote
   */
  select?: Prisma.ClubVoteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ClubVote
   */
  omit?: Prisma.ClubVoteOmit<ExtArgs> | null
  /**
   * The data used to update ClubVotes.
   */
  data: Prisma.XOR<Prisma.ClubVoteUpdateManyMutationInput, Prisma.ClubVoteUncheckedUpdateManyInput>
  /**
   * Filter which ClubVotes to update
   */
  where?: Prisma.ClubVoteWhereInput
  /**
   * Limit how many ClubVotes to update.
   */
  limit?: number
}

/**
 * ClubVote upsert
 */
export type ClubVoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubVote
   */
  select?: Prisma.ClubVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClubVote
   */
  omit?: Prisma.ClubVoteOmit<ExtArgs> | null
  /**
   * The filter to search for the ClubVote to update in case it exists.
   */
  where: Prisma.ClubVoteWhereUniqueInput
  /**
   * In case the ClubVote found by the `where` argument doesn't exist, create a new ClubVote with this data.
   */
  create: Prisma.XOR<Prisma.ClubVoteCreateInput, Prisma.ClubVoteUncheckedCreateInput>
  /**
   * In case the ClubVote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClubVoteUpdateInput, Prisma.ClubVoteUncheckedUpdateInput>
}

/**
 * ClubVote delete
 */
export type ClubVoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubVote
   */
  select?: Prisma.ClubVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClubVote
   */
  omit?: Prisma.ClubVoteOmit<ExtArgs> | null
  /**
   * Filter which ClubVote to delete.
   */
  where: Prisma.ClubVoteWhereUniqueInput
}

/**
 * ClubVote deleteMany
 */
export type ClubVoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClubVotes to delete
   */
  where?: Prisma.ClubVoteWhereInput
  /**
   * Limit how many ClubVotes to delete.
   */
  limit?: number
}

/**
 * ClubVote without action
 */
export type ClubVoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubVote
   */
  select?: Prisma.ClubVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClubVote
   */
  omit?: Prisma.ClubVoteOmit<ExtArgs> | null
}
