
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `KeyValueItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model KeyValueItem
 * 
 */
export type KeyValueItemModel = runtime.Types.Result.DefaultSelection<Prisma.$KeyValueItemPayload>

export type AggregateKeyValueItem = {
  _count: KeyValueItemCountAggregateOutputType | null
  _min: KeyValueItemMinAggregateOutputType | null
  _max: KeyValueItemMaxAggregateOutputType | null
}

export type KeyValueItemMinAggregateOutputType = {
  key: string | null
}

export type KeyValueItemMaxAggregateOutputType = {
  key: string | null
}

export type KeyValueItemCountAggregateOutputType = {
  key: number
  value: number
  _all: number
}


export type KeyValueItemMinAggregateInputType = {
  key?: true
}

export type KeyValueItemMaxAggregateInputType = {
  key?: true
}

export type KeyValueItemCountAggregateInputType = {
  key?: true
  value?: true
  _all?: true
}

export type KeyValueItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KeyValueItem to aggregate.
   */
  where?: Prisma.KeyValueItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KeyValueItems to fetch.
   */
  orderBy?: Prisma.KeyValueItemOrderByWithRelationInput | Prisma.KeyValueItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KeyValueItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KeyValueItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KeyValueItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KeyValueItems
  **/
  _count?: true | KeyValueItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KeyValueItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KeyValueItemMaxAggregateInputType
}

export type GetKeyValueItemAggregateType<T extends KeyValueItemAggregateArgs> = {
      [P in keyof T & keyof AggregateKeyValueItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKeyValueItem[P]>
    : Prisma.GetScalarType<T[P], AggregateKeyValueItem[P]>
}




export type KeyValueItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KeyValueItemWhereInput
  orderBy?: Prisma.KeyValueItemOrderByWithAggregationInput | Prisma.KeyValueItemOrderByWithAggregationInput[]
  by: Prisma.KeyValueItemScalarFieldEnum[] | Prisma.KeyValueItemScalarFieldEnum
  having?: Prisma.KeyValueItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KeyValueItemCountAggregateInputType | true
  _min?: KeyValueItemMinAggregateInputType
  _max?: KeyValueItemMaxAggregateInputType
}

export type KeyValueItemGroupByOutputType = {
  key: string
  value: runtime.JsonValue
  _count: KeyValueItemCountAggregateOutputType | null
  _min: KeyValueItemMinAggregateOutputType | null
  _max: KeyValueItemMaxAggregateOutputType | null
}

type GetKeyValueItemGroupByPayload<T extends KeyValueItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KeyValueItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KeyValueItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KeyValueItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KeyValueItemGroupByOutputType[P]>
      }
    >
  >



export type KeyValueItemWhereInput = {
  AND?: Prisma.KeyValueItemWhereInput | Prisma.KeyValueItemWhereInput[]
  OR?: Prisma.KeyValueItemWhereInput[]
  NOT?: Prisma.KeyValueItemWhereInput | Prisma.KeyValueItemWhereInput[]
  key?: Prisma.StringFilter<"KeyValueItem"> | string
  value?: Prisma.JsonFilter<"KeyValueItem">
}

export type KeyValueItemOrderByWithRelationInput = {
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type KeyValueItemWhereUniqueInput = Prisma.AtLeast<{
  key?: string
  AND?: Prisma.KeyValueItemWhereInput | Prisma.KeyValueItemWhereInput[]
  OR?: Prisma.KeyValueItemWhereInput[]
  NOT?: Prisma.KeyValueItemWhereInput | Prisma.KeyValueItemWhereInput[]
  value?: Prisma.JsonFilter<"KeyValueItem">
}, "key">

export type KeyValueItemOrderByWithAggregationInput = {
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
  _count?: Prisma.KeyValueItemCountOrderByAggregateInput
  _max?: Prisma.KeyValueItemMaxOrderByAggregateInput
  _min?: Prisma.KeyValueItemMinOrderByAggregateInput
}

export type KeyValueItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.KeyValueItemScalarWhereWithAggregatesInput | Prisma.KeyValueItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.KeyValueItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KeyValueItemScalarWhereWithAggregatesInput | Prisma.KeyValueItemScalarWhereWithAggregatesInput[]
  key?: Prisma.StringWithAggregatesFilter<"KeyValueItem"> | string
  value?: Prisma.JsonWithAggregatesFilter<"KeyValueItem">
}

export type KeyValueItemCreateInput = {
  key: string
  value: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type KeyValueItemUncheckedCreateInput = {
  key: string
  value: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type KeyValueItemUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type KeyValueItemUncheckedUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type KeyValueItemCreateManyInput = {
  key: string
  value: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type KeyValueItemUpdateManyMutationInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type KeyValueItemUncheckedUpdateManyInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type KeyValueItemCountOrderByAggregateInput = {
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type KeyValueItemMaxOrderByAggregateInput = {
  key?: Prisma.SortOrder
}

export type KeyValueItemMinOrderByAggregateInput = {
  key?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}



export type KeyValueItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  value?: boolean
}, ExtArgs["result"]["keyValueItem"]>

export type KeyValueItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  value?: boolean
}, ExtArgs["result"]["keyValueItem"]>

export type KeyValueItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  value?: boolean
}, ExtArgs["result"]["keyValueItem"]>

export type KeyValueItemSelectScalar = {
  key?: boolean
  value?: boolean
}

export type KeyValueItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"key" | "value", ExtArgs["result"]["keyValueItem"]>

export type $KeyValueItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KeyValueItem"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    key: string
    value: runtime.JsonValue
  }, ExtArgs["result"]["keyValueItem"]>
  composites: {}
}

export type KeyValueItemGetPayload<S extends boolean | null | undefined | KeyValueItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KeyValueItemPayload, S>

export type KeyValueItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KeyValueItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KeyValueItemCountAggregateInputType | true
  }

export interface KeyValueItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KeyValueItem'], meta: { name: 'KeyValueItem' } }
  /**
   * Find zero or one KeyValueItem that matches the filter.
   * @param {KeyValueItemFindUniqueArgs} args - Arguments to find a KeyValueItem
   * @example
   * // Get one KeyValueItem
   * const keyValueItem = await prisma.keyValueItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KeyValueItemFindUniqueArgs>(args: Prisma.SelectSubset<T, KeyValueItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KeyValueItemClient<runtime.Types.Result.GetResult<Prisma.$KeyValueItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KeyValueItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KeyValueItemFindUniqueOrThrowArgs} args - Arguments to find a KeyValueItem
   * @example
   * // Get one KeyValueItem
   * const keyValueItem = await prisma.keyValueItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KeyValueItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KeyValueItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KeyValueItemClient<runtime.Types.Result.GetResult<Prisma.$KeyValueItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KeyValueItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KeyValueItemFindFirstArgs} args - Arguments to find a KeyValueItem
   * @example
   * // Get one KeyValueItem
   * const keyValueItem = await prisma.keyValueItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KeyValueItemFindFirstArgs>(args?: Prisma.SelectSubset<T, KeyValueItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__KeyValueItemClient<runtime.Types.Result.GetResult<Prisma.$KeyValueItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KeyValueItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KeyValueItemFindFirstOrThrowArgs} args - Arguments to find a KeyValueItem
   * @example
   * // Get one KeyValueItem
   * const keyValueItem = await prisma.keyValueItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KeyValueItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KeyValueItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KeyValueItemClient<runtime.Types.Result.GetResult<Prisma.$KeyValueItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KeyValueItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KeyValueItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KeyValueItems
   * const keyValueItems = await prisma.keyValueItem.findMany()
   * 
   * // Get first 10 KeyValueItems
   * const keyValueItems = await prisma.keyValueItem.findMany({ take: 10 })
   * 
   * // Only select the `key`
   * const keyValueItemWithKeyOnly = await prisma.keyValueItem.findMany({ select: { key: true } })
   * 
   */
  findMany<T extends KeyValueItemFindManyArgs>(args?: Prisma.SelectSubset<T, KeyValueItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KeyValueItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a KeyValueItem.
   * @param {KeyValueItemCreateArgs} args - Arguments to create a KeyValueItem.
   * @example
   * // Create one KeyValueItem
   * const KeyValueItem = await prisma.keyValueItem.create({
   *   data: {
   *     // ... data to create a KeyValueItem
   *   }
   * })
   * 
   */
  create<T extends KeyValueItemCreateArgs>(args: Prisma.SelectSubset<T, KeyValueItemCreateArgs<ExtArgs>>): Prisma.Prisma__KeyValueItemClient<runtime.Types.Result.GetResult<Prisma.$KeyValueItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many KeyValueItems.
   * @param {KeyValueItemCreateManyArgs} args - Arguments to create many KeyValueItems.
   * @example
   * // Create many KeyValueItems
   * const keyValueItem = await prisma.keyValueItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KeyValueItemCreateManyArgs>(args?: Prisma.SelectSubset<T, KeyValueItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many KeyValueItems and returns the data saved in the database.
   * @param {KeyValueItemCreateManyAndReturnArgs} args - Arguments to create many KeyValueItems.
   * @example
   * // Create many KeyValueItems
   * const keyValueItem = await prisma.keyValueItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many KeyValueItems and only return the `key`
   * const keyValueItemWithKeyOnly = await prisma.keyValueItem.createManyAndReturn({
   *   select: { key: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KeyValueItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KeyValueItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KeyValueItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a KeyValueItem.
   * @param {KeyValueItemDeleteArgs} args - Arguments to delete one KeyValueItem.
   * @example
   * // Delete one KeyValueItem
   * const KeyValueItem = await prisma.keyValueItem.delete({
   *   where: {
   *     // ... filter to delete one KeyValueItem
   *   }
   * })
   * 
   */
  delete<T extends KeyValueItemDeleteArgs>(args: Prisma.SelectSubset<T, KeyValueItemDeleteArgs<ExtArgs>>): Prisma.Prisma__KeyValueItemClient<runtime.Types.Result.GetResult<Prisma.$KeyValueItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KeyValueItem.
   * @param {KeyValueItemUpdateArgs} args - Arguments to update one KeyValueItem.
   * @example
   * // Update one KeyValueItem
   * const keyValueItem = await prisma.keyValueItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KeyValueItemUpdateArgs>(args: Prisma.SelectSubset<T, KeyValueItemUpdateArgs<ExtArgs>>): Prisma.Prisma__KeyValueItemClient<runtime.Types.Result.GetResult<Prisma.$KeyValueItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KeyValueItems.
   * @param {KeyValueItemDeleteManyArgs} args - Arguments to filter KeyValueItems to delete.
   * @example
   * // Delete a few KeyValueItems
   * const { count } = await prisma.keyValueItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KeyValueItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, KeyValueItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KeyValueItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KeyValueItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KeyValueItems
   * const keyValueItem = await prisma.keyValueItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KeyValueItemUpdateManyArgs>(args: Prisma.SelectSubset<T, KeyValueItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KeyValueItems and returns the data updated in the database.
   * @param {KeyValueItemUpdateManyAndReturnArgs} args - Arguments to update many KeyValueItems.
   * @example
   * // Update many KeyValueItems
   * const keyValueItem = await prisma.keyValueItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more KeyValueItems and only return the `key`
   * const keyValueItemWithKeyOnly = await prisma.keyValueItem.updateManyAndReturn({
   *   select: { key: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KeyValueItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KeyValueItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KeyValueItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one KeyValueItem.
   * @param {KeyValueItemUpsertArgs} args - Arguments to update or create a KeyValueItem.
   * @example
   * // Update or create a KeyValueItem
   * const keyValueItem = await prisma.keyValueItem.upsert({
   *   create: {
   *     // ... data to create a KeyValueItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the KeyValueItem we want to update
   *   }
   * })
   */
  upsert<T extends KeyValueItemUpsertArgs>(args: Prisma.SelectSubset<T, KeyValueItemUpsertArgs<ExtArgs>>): Prisma.Prisma__KeyValueItemClient<runtime.Types.Result.GetResult<Prisma.$KeyValueItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of KeyValueItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KeyValueItemCountArgs} args - Arguments to filter KeyValueItems to count.
   * @example
   * // Count the number of KeyValueItems
   * const count = await prisma.keyValueItem.count({
   *   where: {
   *     // ... the filter for the KeyValueItems we want to count
   *   }
   * })
  **/
  count<T extends KeyValueItemCountArgs>(
    args?: Prisma.Subset<T, KeyValueItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KeyValueItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KeyValueItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KeyValueItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KeyValueItemAggregateArgs>(args: Prisma.Subset<T, KeyValueItemAggregateArgs>): Prisma.PrismaPromise<GetKeyValueItemAggregateType<T>>

  /**
   * Group by KeyValueItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KeyValueItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KeyValueItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KeyValueItemGroupByArgs['orderBy'] }
      : { orderBy?: KeyValueItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KeyValueItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKeyValueItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KeyValueItem model
 */
readonly fields: KeyValueItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KeyValueItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KeyValueItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KeyValueItem model
 */
export interface KeyValueItemFieldRefs {
  readonly key: Prisma.FieldRef<"KeyValueItem", 'String'>
  readonly value: Prisma.FieldRef<"KeyValueItem", 'Json'>
}
    

// Custom InputTypes
/**
 * KeyValueItem findUnique
 */
export type KeyValueItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KeyValueItem
   */
  select?: Prisma.KeyValueItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KeyValueItem
   */
  omit?: Prisma.KeyValueItemOmit<ExtArgs> | null
  /**
   * Filter, which KeyValueItem to fetch.
   */
  where: Prisma.KeyValueItemWhereUniqueInput
}

/**
 * KeyValueItem findUniqueOrThrow
 */
export type KeyValueItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KeyValueItem
   */
  select?: Prisma.KeyValueItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KeyValueItem
   */
  omit?: Prisma.KeyValueItemOmit<ExtArgs> | null
  /**
   * Filter, which KeyValueItem to fetch.
   */
  where: Prisma.KeyValueItemWhereUniqueInput
}

/**
 * KeyValueItem findFirst
 */
export type KeyValueItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KeyValueItem
   */
  select?: Prisma.KeyValueItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KeyValueItem
   */
  omit?: Prisma.KeyValueItemOmit<ExtArgs> | null
  /**
   * Filter, which KeyValueItem to fetch.
   */
  where?: Prisma.KeyValueItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KeyValueItems to fetch.
   */
  orderBy?: Prisma.KeyValueItemOrderByWithRelationInput | Prisma.KeyValueItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KeyValueItems.
   */
  cursor?: Prisma.KeyValueItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KeyValueItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KeyValueItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KeyValueItems.
   */
  distinct?: Prisma.KeyValueItemScalarFieldEnum | Prisma.KeyValueItemScalarFieldEnum[]
}

/**
 * KeyValueItem findFirstOrThrow
 */
export type KeyValueItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KeyValueItem
   */
  select?: Prisma.KeyValueItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KeyValueItem
   */
  omit?: Prisma.KeyValueItemOmit<ExtArgs> | null
  /**
   * Filter, which KeyValueItem to fetch.
   */
  where?: Prisma.KeyValueItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KeyValueItems to fetch.
   */
  orderBy?: Prisma.KeyValueItemOrderByWithRelationInput | Prisma.KeyValueItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KeyValueItems.
   */
  cursor?: Prisma.KeyValueItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KeyValueItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KeyValueItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KeyValueItems.
   */
  distinct?: Prisma.KeyValueItemScalarFieldEnum | Prisma.KeyValueItemScalarFieldEnum[]
}

/**
 * KeyValueItem findMany
 */
export type KeyValueItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KeyValueItem
   */
  select?: Prisma.KeyValueItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KeyValueItem
   */
  omit?: Prisma.KeyValueItemOmit<ExtArgs> | null
  /**
   * Filter, which KeyValueItems to fetch.
   */
  where?: Prisma.KeyValueItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KeyValueItems to fetch.
   */
  orderBy?: Prisma.KeyValueItemOrderByWithRelationInput | Prisma.KeyValueItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KeyValueItems.
   */
  cursor?: Prisma.KeyValueItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KeyValueItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KeyValueItems.
   */
  skip?: number
  distinct?: Prisma.KeyValueItemScalarFieldEnum | Prisma.KeyValueItemScalarFieldEnum[]
}

/**
 * KeyValueItem create
 */
export type KeyValueItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KeyValueItem
   */
  select?: Prisma.KeyValueItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KeyValueItem
   */
  omit?: Prisma.KeyValueItemOmit<ExtArgs> | null
  /**
   * The data needed to create a KeyValueItem.
   */
  data: Prisma.XOR<Prisma.KeyValueItemCreateInput, Prisma.KeyValueItemUncheckedCreateInput>
}

/**
 * KeyValueItem createMany
 */
export type KeyValueItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many KeyValueItems.
   */
  data: Prisma.KeyValueItemCreateManyInput | Prisma.KeyValueItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KeyValueItem createManyAndReturn
 */
export type KeyValueItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KeyValueItem
   */
  select?: Prisma.KeyValueItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KeyValueItem
   */
  omit?: Prisma.KeyValueItemOmit<ExtArgs> | null
  /**
   * The data used to create many KeyValueItems.
   */
  data: Prisma.KeyValueItemCreateManyInput | Prisma.KeyValueItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KeyValueItem update
 */
export type KeyValueItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KeyValueItem
   */
  select?: Prisma.KeyValueItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KeyValueItem
   */
  omit?: Prisma.KeyValueItemOmit<ExtArgs> | null
  /**
   * The data needed to update a KeyValueItem.
   */
  data: Prisma.XOR<Prisma.KeyValueItemUpdateInput, Prisma.KeyValueItemUncheckedUpdateInput>
  /**
   * Choose, which KeyValueItem to update.
   */
  where: Prisma.KeyValueItemWhereUniqueInput
}

/**
 * KeyValueItem updateMany
 */
export type KeyValueItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KeyValueItems.
   */
  data: Prisma.XOR<Prisma.KeyValueItemUpdateManyMutationInput, Prisma.KeyValueItemUncheckedUpdateManyInput>
  /**
   * Filter which KeyValueItems to update
   */
  where?: Prisma.KeyValueItemWhereInput
  /**
   * Limit how many KeyValueItems to update.
   */
  limit?: number
}

/**
 * KeyValueItem updateManyAndReturn
 */
export type KeyValueItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KeyValueItem
   */
  select?: Prisma.KeyValueItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KeyValueItem
   */
  omit?: Prisma.KeyValueItemOmit<ExtArgs> | null
  /**
   * The data used to update KeyValueItems.
   */
  data: Prisma.XOR<Prisma.KeyValueItemUpdateManyMutationInput, Prisma.KeyValueItemUncheckedUpdateManyInput>
  /**
   * Filter which KeyValueItems to update
   */
  where?: Prisma.KeyValueItemWhereInput
  /**
   * Limit how many KeyValueItems to update.
   */
  limit?: number
}

/**
 * KeyValueItem upsert
 */
export type KeyValueItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KeyValueItem
   */
  select?: Prisma.KeyValueItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KeyValueItem
   */
  omit?: Prisma.KeyValueItemOmit<ExtArgs> | null
  /**
   * The filter to search for the KeyValueItem to update in case it exists.
   */
  where: Prisma.KeyValueItemWhereUniqueInput
  /**
   * In case the KeyValueItem found by the `where` argument doesn't exist, create a new KeyValueItem with this data.
   */
  create: Prisma.XOR<Prisma.KeyValueItemCreateInput, Prisma.KeyValueItemUncheckedCreateInput>
  /**
   * In case the KeyValueItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KeyValueItemUpdateInput, Prisma.KeyValueItemUncheckedUpdateInput>
}

/**
 * KeyValueItem delete
 */
export type KeyValueItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KeyValueItem
   */
  select?: Prisma.KeyValueItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KeyValueItem
   */
  omit?: Prisma.KeyValueItemOmit<ExtArgs> | null
  /**
   * Filter which KeyValueItem to delete.
   */
  where: Prisma.KeyValueItemWhereUniqueInput
}

/**
 * KeyValueItem deleteMany
 */
export type KeyValueItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KeyValueItems to delete
   */
  where?: Prisma.KeyValueItemWhereInput
  /**
   * Limit how many KeyValueItems to delete.
   */
  limit?: number
}

/**
 * KeyValueItem without action
 */
export type KeyValueItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KeyValueItem
   */
  select?: Prisma.KeyValueItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KeyValueItem
   */
  omit?: Prisma.KeyValueItemOmit<ExtArgs> | null
}
