
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Mute` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Mute
 * 
 */
export type MuteModel = runtime.Types.Result.DefaultSelection<Prisma.$MutePayload>

export type AggregateMute = {
  _count: MuteCountAggregateOutputType | null
  _avg: MuteAvgAggregateOutputType | null
  _sum: MuteSumAggregateOutputType | null
  _min: MuteMinAggregateOutputType | null
  _max: MuteMaxAggregateOutputType | null
}

export type MuteAvgAggregateOutputType = {
  id: number | null
}

export type MuteSumAggregateOutputType = {
  id: number | null
}

export type MuteMinAggregateOutputType = {
  id: number | null
  guildId: string | null
  memberId: string | null
  endsAt: Date | null
}

export type MuteMaxAggregateOutputType = {
  id: number | null
  guildId: string | null
  memberId: string | null
  endsAt: Date | null
}

export type MuteCountAggregateOutputType = {
  id: number
  guildId: number
  memberId: number
  endsAt: number
  _all: number
}


export type MuteAvgAggregateInputType = {
  id?: true
}

export type MuteSumAggregateInputType = {
  id?: true
}

export type MuteMinAggregateInputType = {
  id?: true
  guildId?: true
  memberId?: true
  endsAt?: true
}

export type MuteMaxAggregateInputType = {
  id?: true
  guildId?: true
  memberId?: true
  endsAt?: true
}

export type MuteCountAggregateInputType = {
  id?: true
  guildId?: true
  memberId?: true
  endsAt?: true
  _all?: true
}

export type MuteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Mute to aggregate.
   */
  where?: Prisma.MuteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mutes to fetch.
   */
  orderBy?: Prisma.MuteOrderByWithRelationInput | Prisma.MuteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MuteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mutes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mutes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Mutes
  **/
  _count?: true | MuteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MuteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MuteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MuteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MuteMaxAggregateInputType
}

export type GetMuteAggregateType<T extends MuteAggregateArgs> = {
      [P in keyof T & keyof AggregateMute]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMute[P]>
    : Prisma.GetScalarType<T[P], AggregateMute[P]>
}




export type MuteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MuteWhereInput
  orderBy?: Prisma.MuteOrderByWithAggregationInput | Prisma.MuteOrderByWithAggregationInput[]
  by: Prisma.MuteScalarFieldEnum[] | Prisma.MuteScalarFieldEnum
  having?: Prisma.MuteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MuteCountAggregateInputType | true
  _avg?: MuteAvgAggregateInputType
  _sum?: MuteSumAggregateInputType
  _min?: MuteMinAggregateInputType
  _max?: MuteMaxAggregateInputType
}

export type MuteGroupByOutputType = {
  id: number
  guildId: string
  memberId: string
  endsAt: Date
  _count: MuteCountAggregateOutputType | null
  _avg: MuteAvgAggregateOutputType | null
  _sum: MuteSumAggregateOutputType | null
  _min: MuteMinAggregateOutputType | null
  _max: MuteMaxAggregateOutputType | null
}

type GetMuteGroupByPayload<T extends MuteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MuteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MuteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MuteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MuteGroupByOutputType[P]>
      }
    >
  >



export type MuteWhereInput = {
  AND?: Prisma.MuteWhereInput | Prisma.MuteWhereInput[]
  OR?: Prisma.MuteWhereInput[]
  NOT?: Prisma.MuteWhereInput | Prisma.MuteWhereInput[]
  id?: Prisma.IntFilter<"Mute"> | number
  guildId?: Prisma.StringFilter<"Mute"> | string
  memberId?: Prisma.StringFilter<"Mute"> | string
  endsAt?: Prisma.DateTimeFilter<"Mute"> | Date | string
}

export type MuteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
}

export type MuteWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MuteWhereInput | Prisma.MuteWhereInput[]
  OR?: Prisma.MuteWhereInput[]
  NOT?: Prisma.MuteWhereInput | Prisma.MuteWhereInput[]
  guildId?: Prisma.StringFilter<"Mute"> | string
  memberId?: Prisma.StringFilter<"Mute"> | string
  endsAt?: Prisma.DateTimeFilter<"Mute"> | Date | string
}, "id">

export type MuteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  _count?: Prisma.MuteCountOrderByAggregateInput
  _avg?: Prisma.MuteAvgOrderByAggregateInput
  _max?: Prisma.MuteMaxOrderByAggregateInput
  _min?: Prisma.MuteMinOrderByAggregateInput
  _sum?: Prisma.MuteSumOrderByAggregateInput
}

export type MuteScalarWhereWithAggregatesInput = {
  AND?: Prisma.MuteScalarWhereWithAggregatesInput | Prisma.MuteScalarWhereWithAggregatesInput[]
  OR?: Prisma.MuteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MuteScalarWhereWithAggregatesInput | Prisma.MuteScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Mute"> | number
  guildId?: Prisma.StringWithAggregatesFilter<"Mute"> | string
  memberId?: Prisma.StringWithAggregatesFilter<"Mute"> | string
  endsAt?: Prisma.DateTimeWithAggregatesFilter<"Mute"> | Date | string
}

export type MuteCreateInput = {
  guildId: string
  memberId: string
  endsAt: Date | string
}

export type MuteUncheckedCreateInput = {
  id?: number
  guildId: string
  memberId: string
  endsAt: Date | string
}

export type MuteUpdateInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MuteUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MuteCreateManyInput = {
  id?: number
  guildId: string
  memberId: string
  endsAt: Date | string
}

export type MuteUpdateManyMutationInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MuteUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MuteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
}

export type MuteAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MuteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
}

export type MuteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
}

export type MuteSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type MuteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  memberId?: boolean
  endsAt?: boolean
}, ExtArgs["result"]["mute"]>

export type MuteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  memberId?: boolean
  endsAt?: boolean
}, ExtArgs["result"]["mute"]>

export type MuteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  memberId?: boolean
  endsAt?: boolean
}, ExtArgs["result"]["mute"]>

export type MuteSelectScalar = {
  id?: boolean
  guildId?: boolean
  memberId?: boolean
  endsAt?: boolean
}

export type MuteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "guildId" | "memberId" | "endsAt", ExtArgs["result"]["mute"]>

export type $MutePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Mute"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    guildId: string
    memberId: string
    endsAt: Date
  }, ExtArgs["result"]["mute"]>
  composites: {}
}

export type MuteGetPayload<S extends boolean | null | undefined | MuteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MutePayload, S>

export type MuteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MuteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MuteCountAggregateInputType | true
  }

export interface MuteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Mute'], meta: { name: 'Mute' } }
  /**
   * Find zero or one Mute that matches the filter.
   * @param {MuteFindUniqueArgs} args - Arguments to find a Mute
   * @example
   * // Get one Mute
   * const mute = await prisma.mute.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MuteFindUniqueArgs>(args: Prisma.SelectSubset<T, MuteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MuteClient<runtime.Types.Result.GetResult<Prisma.$MutePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Mute that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MuteFindUniqueOrThrowArgs} args - Arguments to find a Mute
   * @example
   * // Get one Mute
   * const mute = await prisma.mute.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MuteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MuteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MuteClient<runtime.Types.Result.GetResult<Prisma.$MutePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mute that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuteFindFirstArgs} args - Arguments to find a Mute
   * @example
   * // Get one Mute
   * const mute = await prisma.mute.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MuteFindFirstArgs>(args?: Prisma.SelectSubset<T, MuteFindFirstArgs<ExtArgs>>): Prisma.Prisma__MuteClient<runtime.Types.Result.GetResult<Prisma.$MutePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mute that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuteFindFirstOrThrowArgs} args - Arguments to find a Mute
   * @example
   * // Get one Mute
   * const mute = await prisma.mute.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MuteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MuteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MuteClient<runtime.Types.Result.GetResult<Prisma.$MutePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Mutes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Mutes
   * const mutes = await prisma.mute.findMany()
   * 
   * // Get first 10 Mutes
   * const mutes = await prisma.mute.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const muteWithIdOnly = await prisma.mute.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MuteFindManyArgs>(args?: Prisma.SelectSubset<T, MuteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MutePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Mute.
   * @param {MuteCreateArgs} args - Arguments to create a Mute.
   * @example
   * // Create one Mute
   * const Mute = await prisma.mute.create({
   *   data: {
   *     // ... data to create a Mute
   *   }
   * })
   * 
   */
  create<T extends MuteCreateArgs>(args: Prisma.SelectSubset<T, MuteCreateArgs<ExtArgs>>): Prisma.Prisma__MuteClient<runtime.Types.Result.GetResult<Prisma.$MutePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Mutes.
   * @param {MuteCreateManyArgs} args - Arguments to create many Mutes.
   * @example
   * // Create many Mutes
   * const mute = await prisma.mute.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MuteCreateManyArgs>(args?: Prisma.SelectSubset<T, MuteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Mutes and returns the data saved in the database.
   * @param {MuteCreateManyAndReturnArgs} args - Arguments to create many Mutes.
   * @example
   * // Create many Mutes
   * const mute = await prisma.mute.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Mutes and only return the `id`
   * const muteWithIdOnly = await prisma.mute.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MuteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MuteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MutePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Mute.
   * @param {MuteDeleteArgs} args - Arguments to delete one Mute.
   * @example
   * // Delete one Mute
   * const Mute = await prisma.mute.delete({
   *   where: {
   *     // ... filter to delete one Mute
   *   }
   * })
   * 
   */
  delete<T extends MuteDeleteArgs>(args: Prisma.SelectSubset<T, MuteDeleteArgs<ExtArgs>>): Prisma.Prisma__MuteClient<runtime.Types.Result.GetResult<Prisma.$MutePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Mute.
   * @param {MuteUpdateArgs} args - Arguments to update one Mute.
   * @example
   * // Update one Mute
   * const mute = await prisma.mute.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MuteUpdateArgs>(args: Prisma.SelectSubset<T, MuteUpdateArgs<ExtArgs>>): Prisma.Prisma__MuteClient<runtime.Types.Result.GetResult<Prisma.$MutePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Mutes.
   * @param {MuteDeleteManyArgs} args - Arguments to filter Mutes to delete.
   * @example
   * // Delete a few Mutes
   * const { count } = await prisma.mute.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MuteDeleteManyArgs>(args?: Prisma.SelectSubset<T, MuteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mutes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Mutes
   * const mute = await prisma.mute.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MuteUpdateManyArgs>(args: Prisma.SelectSubset<T, MuteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mutes and returns the data updated in the database.
   * @param {MuteUpdateManyAndReturnArgs} args - Arguments to update many Mutes.
   * @example
   * // Update many Mutes
   * const mute = await prisma.mute.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Mutes and only return the `id`
   * const muteWithIdOnly = await prisma.mute.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MuteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MuteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MutePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Mute.
   * @param {MuteUpsertArgs} args - Arguments to update or create a Mute.
   * @example
   * // Update or create a Mute
   * const mute = await prisma.mute.upsert({
   *   create: {
   *     // ... data to create a Mute
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Mute we want to update
   *   }
   * })
   */
  upsert<T extends MuteUpsertArgs>(args: Prisma.SelectSubset<T, MuteUpsertArgs<ExtArgs>>): Prisma.Prisma__MuteClient<runtime.Types.Result.GetResult<Prisma.$MutePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Mutes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuteCountArgs} args - Arguments to filter Mutes to count.
   * @example
   * // Count the number of Mutes
   * const count = await prisma.mute.count({
   *   where: {
   *     // ... the filter for the Mutes we want to count
   *   }
   * })
  **/
  count<T extends MuteCountArgs>(
    args?: Prisma.Subset<T, MuteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MuteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Mute.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MuteAggregateArgs>(args: Prisma.Subset<T, MuteAggregateArgs>): Prisma.PrismaPromise<GetMuteAggregateType<T>>

  /**
   * Group by Mute.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MuteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MuteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MuteGroupByArgs['orderBy'] }
      : { orderBy?: MuteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MuteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMuteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Mute model
 */
readonly fields: MuteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Mute.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MuteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Mute model
 */
export interface MuteFieldRefs {
  readonly id: Prisma.FieldRef<"Mute", 'Int'>
  readonly guildId: Prisma.FieldRef<"Mute", 'String'>
  readonly memberId: Prisma.FieldRef<"Mute", 'String'>
  readonly endsAt: Prisma.FieldRef<"Mute", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Mute findUnique
 */
export type MuteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mute
   */
  select?: Prisma.MuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mute
   */
  omit?: Prisma.MuteOmit<ExtArgs> | null
  /**
   * Filter, which Mute to fetch.
   */
  where: Prisma.MuteWhereUniqueInput
}

/**
 * Mute findUniqueOrThrow
 */
export type MuteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mute
   */
  select?: Prisma.MuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mute
   */
  omit?: Prisma.MuteOmit<ExtArgs> | null
  /**
   * Filter, which Mute to fetch.
   */
  where: Prisma.MuteWhereUniqueInput
}

/**
 * Mute findFirst
 */
export type MuteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mute
   */
  select?: Prisma.MuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mute
   */
  omit?: Prisma.MuteOmit<ExtArgs> | null
  /**
   * Filter, which Mute to fetch.
   */
  where?: Prisma.MuteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mutes to fetch.
   */
  orderBy?: Prisma.MuteOrderByWithRelationInput | Prisma.MuteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Mutes.
   */
  cursor?: Prisma.MuteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mutes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mutes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mutes.
   */
  distinct?: Prisma.MuteScalarFieldEnum | Prisma.MuteScalarFieldEnum[]
}

/**
 * Mute findFirstOrThrow
 */
export type MuteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mute
   */
  select?: Prisma.MuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mute
   */
  omit?: Prisma.MuteOmit<ExtArgs> | null
  /**
   * Filter, which Mute to fetch.
   */
  where?: Prisma.MuteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mutes to fetch.
   */
  orderBy?: Prisma.MuteOrderByWithRelationInput | Prisma.MuteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Mutes.
   */
  cursor?: Prisma.MuteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mutes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mutes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mutes.
   */
  distinct?: Prisma.MuteScalarFieldEnum | Prisma.MuteScalarFieldEnum[]
}

/**
 * Mute findMany
 */
export type MuteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mute
   */
  select?: Prisma.MuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mute
   */
  omit?: Prisma.MuteOmit<ExtArgs> | null
  /**
   * Filter, which Mutes to fetch.
   */
  where?: Prisma.MuteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mutes to fetch.
   */
  orderBy?: Prisma.MuteOrderByWithRelationInput | Prisma.MuteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Mutes.
   */
  cursor?: Prisma.MuteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mutes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mutes.
   */
  skip?: number
  distinct?: Prisma.MuteScalarFieldEnum | Prisma.MuteScalarFieldEnum[]
}

/**
 * Mute create
 */
export type MuteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mute
   */
  select?: Prisma.MuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mute
   */
  omit?: Prisma.MuteOmit<ExtArgs> | null
  /**
   * The data needed to create a Mute.
   */
  data: Prisma.XOR<Prisma.MuteCreateInput, Prisma.MuteUncheckedCreateInput>
}

/**
 * Mute createMany
 */
export type MuteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Mutes.
   */
  data: Prisma.MuteCreateManyInput | Prisma.MuteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Mute createManyAndReturn
 */
export type MuteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mute
   */
  select?: Prisma.MuteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Mute
   */
  omit?: Prisma.MuteOmit<ExtArgs> | null
  /**
   * The data used to create many Mutes.
   */
  data: Prisma.MuteCreateManyInput | Prisma.MuteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Mute update
 */
export type MuteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mute
   */
  select?: Prisma.MuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mute
   */
  omit?: Prisma.MuteOmit<ExtArgs> | null
  /**
   * The data needed to update a Mute.
   */
  data: Prisma.XOR<Prisma.MuteUpdateInput, Prisma.MuteUncheckedUpdateInput>
  /**
   * Choose, which Mute to update.
   */
  where: Prisma.MuteWhereUniqueInput
}

/**
 * Mute updateMany
 */
export type MuteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Mutes.
   */
  data: Prisma.XOR<Prisma.MuteUpdateManyMutationInput, Prisma.MuteUncheckedUpdateManyInput>
  /**
   * Filter which Mutes to update
   */
  where?: Prisma.MuteWhereInput
  /**
   * Limit how many Mutes to update.
   */
  limit?: number
}

/**
 * Mute updateManyAndReturn
 */
export type MuteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mute
   */
  select?: Prisma.MuteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Mute
   */
  omit?: Prisma.MuteOmit<ExtArgs> | null
  /**
   * The data used to update Mutes.
   */
  data: Prisma.XOR<Prisma.MuteUpdateManyMutationInput, Prisma.MuteUncheckedUpdateManyInput>
  /**
   * Filter which Mutes to update
   */
  where?: Prisma.MuteWhereInput
  /**
   * Limit how many Mutes to update.
   */
  limit?: number
}

/**
 * Mute upsert
 */
export type MuteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mute
   */
  select?: Prisma.MuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mute
   */
  omit?: Prisma.MuteOmit<ExtArgs> | null
  /**
   * The filter to search for the Mute to update in case it exists.
   */
  where: Prisma.MuteWhereUniqueInput
  /**
   * In case the Mute found by the `where` argument doesn't exist, create a new Mute with this data.
   */
  create: Prisma.XOR<Prisma.MuteCreateInput, Prisma.MuteUncheckedCreateInput>
  /**
   * In case the Mute was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MuteUpdateInput, Prisma.MuteUncheckedUpdateInput>
}

/**
 * Mute delete
 */
export type MuteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mute
   */
  select?: Prisma.MuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mute
   */
  omit?: Prisma.MuteOmit<ExtArgs> | null
  /**
   * Filter which Mute to delete.
   */
  where: Prisma.MuteWhereUniqueInput
}

/**
 * Mute deleteMany
 */
export type MuteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Mutes to delete
   */
  where?: Prisma.MuteWhereInput
  /**
   * Limit how many Mutes to delete.
   */
  limit?: number
}

/**
 * Mute without action
 */
export type MuteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mute
   */
  select?: Prisma.MuteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mute
   */
  omit?: Prisma.MuteOmit<ExtArgs> | null
}
