
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Poll` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Poll
 * 
 */
export type PollModel = runtime.Types.Result.DefaultSelection<Prisma.$PollPayload>

export type AggregatePoll = {
  _count: PollCountAggregateOutputType | null
  _avg: PollAvgAggregateOutputType | null
  _sum: PollSumAggregateOutputType | null
  _min: PollMinAggregateOutputType | null
  _max: PollMaxAggregateOutputType | null
}

export type PollAvgAggregateOutputType = {
  id: number | null
  minValues: number | null
  maxValues: number | null
}

export type PollSumAggregateOutputType = {
  id: number | null
  minValues: number | null
  maxValues: number | null
}

export type PollMinAggregateOutputType = {
  id: number | null
  guildId: string | null
  localId: string | null
  name: string | null
  channelId: string | null
  messsageId: string | null
  active: boolean | null
  minValues: number | null
  maxValues: number | null
  allowChangingVote: boolean | null
  showResults: boolean | null
}

export type PollMaxAggregateOutputType = {
  id: number | null
  guildId: string | null
  localId: string | null
  name: string | null
  channelId: string | null
  messsageId: string | null
  active: boolean | null
  minValues: number | null
  maxValues: number | null
  allowChangingVote: boolean | null
  showResults: boolean | null
}

export type PollCountAggregateOutputType = {
  id: number
  guildId: number
  localId: number
  name: number
  channelId: number
  messsageId: number
  active: number
  options: number
  minValues: number
  maxValues: number
  allowChangingVote: number
  showResults: number
  _all: number
}


export type PollAvgAggregateInputType = {
  id?: true
  minValues?: true
  maxValues?: true
}

export type PollSumAggregateInputType = {
  id?: true
  minValues?: true
  maxValues?: true
}

export type PollMinAggregateInputType = {
  id?: true
  guildId?: true
  localId?: true
  name?: true
  channelId?: true
  messsageId?: true
  active?: true
  minValues?: true
  maxValues?: true
  allowChangingVote?: true
  showResults?: true
}

export type PollMaxAggregateInputType = {
  id?: true
  guildId?: true
  localId?: true
  name?: true
  channelId?: true
  messsageId?: true
  active?: true
  minValues?: true
  maxValues?: true
  allowChangingVote?: true
  showResults?: true
}

export type PollCountAggregateInputType = {
  id?: true
  guildId?: true
  localId?: true
  name?: true
  channelId?: true
  messsageId?: true
  active?: true
  options?: true
  minValues?: true
  maxValues?: true
  allowChangingVote?: true
  showResults?: true
  _all?: true
}

export type PollAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Poll to aggregate.
   */
  where?: Prisma.PollWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Polls to fetch.
   */
  orderBy?: Prisma.PollOrderByWithRelationInput | Prisma.PollOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PollWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Polls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Polls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Polls
  **/
  _count?: true | PollCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PollAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PollSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PollMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PollMaxAggregateInputType
}

export type GetPollAggregateType<T extends PollAggregateArgs> = {
      [P in keyof T & keyof AggregatePoll]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePoll[P]>
    : Prisma.GetScalarType<T[P], AggregatePoll[P]>
}




export type PollGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PollWhereInput
  orderBy?: Prisma.PollOrderByWithAggregationInput | Prisma.PollOrderByWithAggregationInput[]
  by: Prisma.PollScalarFieldEnum[] | Prisma.PollScalarFieldEnum
  having?: Prisma.PollScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PollCountAggregateInputType | true
  _avg?: PollAvgAggregateInputType
  _sum?: PollSumAggregateInputType
  _min?: PollMinAggregateInputType
  _max?: PollMaxAggregateInputType
}

export type PollGroupByOutputType = {
  id: number
  guildId: string
  localId: string
  name: string
  channelId: string
  messsageId: string
  active: boolean
  options: runtime.JsonValue
  minValues: number
  maxValues: number
  allowChangingVote: boolean
  showResults: boolean
  _count: PollCountAggregateOutputType | null
  _avg: PollAvgAggregateOutputType | null
  _sum: PollSumAggregateOutputType | null
  _min: PollMinAggregateOutputType | null
  _max: PollMaxAggregateOutputType | null
}

type GetPollGroupByPayload<T extends PollGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PollGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PollGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PollGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PollGroupByOutputType[P]>
      }
    >
  >



export type PollWhereInput = {
  AND?: Prisma.PollWhereInput | Prisma.PollWhereInput[]
  OR?: Prisma.PollWhereInput[]
  NOT?: Prisma.PollWhereInput | Prisma.PollWhereInput[]
  id?: Prisma.IntFilter<"Poll"> | number
  guildId?: Prisma.StringFilter<"Poll"> | string
  localId?: Prisma.StringFilter<"Poll"> | string
  name?: Prisma.StringFilter<"Poll"> | string
  channelId?: Prisma.StringFilter<"Poll"> | string
  messsageId?: Prisma.StringFilter<"Poll"> | string
  active?: Prisma.BoolFilter<"Poll"> | boolean
  options?: Prisma.JsonFilter<"Poll">
  minValues?: Prisma.IntFilter<"Poll"> | number
  maxValues?: Prisma.IntFilter<"Poll"> | number
  allowChangingVote?: Prisma.BoolFilter<"Poll"> | boolean
  showResults?: Prisma.BoolFilter<"Poll"> | boolean
  votes?: Prisma.VoteListRelationFilter
}

export type PollOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  localId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messsageId?: Prisma.SortOrder
  active?: Prisma.SortOrder
  options?: Prisma.SortOrder
  minValues?: Prisma.SortOrder
  maxValues?: Prisma.SortOrder
  allowChangingVote?: Prisma.SortOrder
  showResults?: Prisma.SortOrder
  votes?: Prisma.VoteOrderByRelationAggregateInput
}

export type PollWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  messsageId?: string
  guildId_localId?: Prisma.PollGuildIdLocalIdCompoundUniqueInput
  AND?: Prisma.PollWhereInput | Prisma.PollWhereInput[]
  OR?: Prisma.PollWhereInput[]
  NOT?: Prisma.PollWhereInput | Prisma.PollWhereInput[]
  guildId?: Prisma.StringFilter<"Poll"> | string
  localId?: Prisma.StringFilter<"Poll"> | string
  name?: Prisma.StringFilter<"Poll"> | string
  channelId?: Prisma.StringFilter<"Poll"> | string
  active?: Prisma.BoolFilter<"Poll"> | boolean
  options?: Prisma.JsonFilter<"Poll">
  minValues?: Prisma.IntFilter<"Poll"> | number
  maxValues?: Prisma.IntFilter<"Poll"> | number
  allowChangingVote?: Prisma.BoolFilter<"Poll"> | boolean
  showResults?: Prisma.BoolFilter<"Poll"> | boolean
  votes?: Prisma.VoteListRelationFilter
}, "id" | "messsageId" | "guildId_localId">

export type PollOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  localId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messsageId?: Prisma.SortOrder
  active?: Prisma.SortOrder
  options?: Prisma.SortOrder
  minValues?: Prisma.SortOrder
  maxValues?: Prisma.SortOrder
  allowChangingVote?: Prisma.SortOrder
  showResults?: Prisma.SortOrder
  _count?: Prisma.PollCountOrderByAggregateInput
  _avg?: Prisma.PollAvgOrderByAggregateInput
  _max?: Prisma.PollMaxOrderByAggregateInput
  _min?: Prisma.PollMinOrderByAggregateInput
  _sum?: Prisma.PollSumOrderByAggregateInput
}

export type PollScalarWhereWithAggregatesInput = {
  AND?: Prisma.PollScalarWhereWithAggregatesInput | Prisma.PollScalarWhereWithAggregatesInput[]
  OR?: Prisma.PollScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PollScalarWhereWithAggregatesInput | Prisma.PollScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Poll"> | number
  guildId?: Prisma.StringWithAggregatesFilter<"Poll"> | string
  localId?: Prisma.StringWithAggregatesFilter<"Poll"> | string
  name?: Prisma.StringWithAggregatesFilter<"Poll"> | string
  channelId?: Prisma.StringWithAggregatesFilter<"Poll"> | string
  messsageId?: Prisma.StringWithAggregatesFilter<"Poll"> | string
  active?: Prisma.BoolWithAggregatesFilter<"Poll"> | boolean
  options?: Prisma.JsonWithAggregatesFilter<"Poll">
  minValues?: Prisma.IntWithAggregatesFilter<"Poll"> | number
  maxValues?: Prisma.IntWithAggregatesFilter<"Poll"> | number
  allowChangingVote?: Prisma.BoolWithAggregatesFilter<"Poll"> | boolean
  showResults?: Prisma.BoolWithAggregatesFilter<"Poll"> | boolean
}

export type PollCreateInput = {
  guildId: string
  localId: string
  name: string
  channelId: string
  messsageId: string
  active?: boolean
  options: Prisma.JsonNullValueInput | runtime.InputJsonValue
  minValues: number
  maxValues: number
  allowChangingVote: boolean
  showResults: boolean
  votes?: Prisma.VoteCreateNestedManyWithoutPollInput
}

export type PollUncheckedCreateInput = {
  id?: number
  guildId: string
  localId: string
  name: string
  channelId: string
  messsageId: string
  active?: boolean
  options: Prisma.JsonNullValueInput | runtime.InputJsonValue
  minValues: number
  maxValues: number
  allowChangingVote: boolean
  showResults: boolean
  votes?: Prisma.VoteUncheckedCreateNestedManyWithoutPollInput
}

export type PollUpdateInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  localId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  messsageId?: Prisma.StringFieldUpdateOperationsInput | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  options?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  minValues?: Prisma.IntFieldUpdateOperationsInput | number
  maxValues?: Prisma.IntFieldUpdateOperationsInput | number
  allowChangingVote?: Prisma.BoolFieldUpdateOperationsInput | boolean
  showResults?: Prisma.BoolFieldUpdateOperationsInput | boolean
  votes?: Prisma.VoteUpdateManyWithoutPollNestedInput
}

export type PollUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  localId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  messsageId?: Prisma.StringFieldUpdateOperationsInput | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  options?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  minValues?: Prisma.IntFieldUpdateOperationsInput | number
  maxValues?: Prisma.IntFieldUpdateOperationsInput | number
  allowChangingVote?: Prisma.BoolFieldUpdateOperationsInput | boolean
  showResults?: Prisma.BoolFieldUpdateOperationsInput | boolean
  votes?: Prisma.VoteUncheckedUpdateManyWithoutPollNestedInput
}

export type PollCreateManyInput = {
  id?: number
  guildId: string
  localId: string
  name: string
  channelId: string
  messsageId: string
  active?: boolean
  options: Prisma.JsonNullValueInput | runtime.InputJsonValue
  minValues: number
  maxValues: number
  allowChangingVote: boolean
  showResults: boolean
}

export type PollUpdateManyMutationInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  localId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  messsageId?: Prisma.StringFieldUpdateOperationsInput | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  options?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  minValues?: Prisma.IntFieldUpdateOperationsInput | number
  maxValues?: Prisma.IntFieldUpdateOperationsInput | number
  allowChangingVote?: Prisma.BoolFieldUpdateOperationsInput | boolean
  showResults?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type PollUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  localId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  messsageId?: Prisma.StringFieldUpdateOperationsInput | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  options?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  minValues?: Prisma.IntFieldUpdateOperationsInput | number
  maxValues?: Prisma.IntFieldUpdateOperationsInput | number
  allowChangingVote?: Prisma.BoolFieldUpdateOperationsInput | boolean
  showResults?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type PollGuildIdLocalIdCompoundUniqueInput = {
  guildId: string
  localId: string
}

export type PollCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  localId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messsageId?: Prisma.SortOrder
  active?: Prisma.SortOrder
  options?: Prisma.SortOrder
  minValues?: Prisma.SortOrder
  maxValues?: Prisma.SortOrder
  allowChangingVote?: Prisma.SortOrder
  showResults?: Prisma.SortOrder
}

export type PollAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  minValues?: Prisma.SortOrder
  maxValues?: Prisma.SortOrder
}

export type PollMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  localId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messsageId?: Prisma.SortOrder
  active?: Prisma.SortOrder
  minValues?: Prisma.SortOrder
  maxValues?: Prisma.SortOrder
  allowChangingVote?: Prisma.SortOrder
  showResults?: Prisma.SortOrder
}

export type PollMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  localId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messsageId?: Prisma.SortOrder
  active?: Prisma.SortOrder
  minValues?: Prisma.SortOrder
  maxValues?: Prisma.SortOrder
  allowChangingVote?: Prisma.SortOrder
  showResults?: Prisma.SortOrder
}

export type PollSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  minValues?: Prisma.SortOrder
  maxValues?: Prisma.SortOrder
}

export type PollScalarRelationFilter = {
  is?: Prisma.PollWhereInput
  isNot?: Prisma.PollWhereInput
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type PollCreateNestedOneWithoutVotesInput = {
  create?: Prisma.XOR<Prisma.PollCreateWithoutVotesInput, Prisma.PollUncheckedCreateWithoutVotesInput>
  connectOrCreate?: Prisma.PollCreateOrConnectWithoutVotesInput
  connect?: Prisma.PollWhereUniqueInput
}

export type PollUpdateOneRequiredWithoutVotesNestedInput = {
  create?: Prisma.XOR<Prisma.PollCreateWithoutVotesInput, Prisma.PollUncheckedCreateWithoutVotesInput>
  connectOrCreate?: Prisma.PollCreateOrConnectWithoutVotesInput
  upsert?: Prisma.PollUpsertWithoutVotesInput
  connect?: Prisma.PollWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PollUpdateToOneWithWhereWithoutVotesInput, Prisma.PollUpdateWithoutVotesInput>, Prisma.PollUncheckedUpdateWithoutVotesInput>
}

export type PollCreateWithoutVotesInput = {
  guildId: string
  localId: string
  name: string
  channelId: string
  messsageId: string
  active?: boolean
  options: Prisma.JsonNullValueInput | runtime.InputJsonValue
  minValues: number
  maxValues: number
  allowChangingVote: boolean
  showResults: boolean
}

export type PollUncheckedCreateWithoutVotesInput = {
  id?: number
  guildId: string
  localId: string
  name: string
  channelId: string
  messsageId: string
  active?: boolean
  options: Prisma.JsonNullValueInput | runtime.InputJsonValue
  minValues: number
  maxValues: number
  allowChangingVote: boolean
  showResults: boolean
}

export type PollCreateOrConnectWithoutVotesInput = {
  where: Prisma.PollWhereUniqueInput
  create: Prisma.XOR<Prisma.PollCreateWithoutVotesInput, Prisma.PollUncheckedCreateWithoutVotesInput>
}

export type PollUpsertWithoutVotesInput = {
  update: Prisma.XOR<Prisma.PollUpdateWithoutVotesInput, Prisma.PollUncheckedUpdateWithoutVotesInput>
  create: Prisma.XOR<Prisma.PollCreateWithoutVotesInput, Prisma.PollUncheckedCreateWithoutVotesInput>
  where?: Prisma.PollWhereInput
}

export type PollUpdateToOneWithWhereWithoutVotesInput = {
  where?: Prisma.PollWhereInput
  data: Prisma.XOR<Prisma.PollUpdateWithoutVotesInput, Prisma.PollUncheckedUpdateWithoutVotesInput>
}

export type PollUpdateWithoutVotesInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  localId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  messsageId?: Prisma.StringFieldUpdateOperationsInput | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  options?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  minValues?: Prisma.IntFieldUpdateOperationsInput | number
  maxValues?: Prisma.IntFieldUpdateOperationsInput | number
  allowChangingVote?: Prisma.BoolFieldUpdateOperationsInput | boolean
  showResults?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type PollUncheckedUpdateWithoutVotesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  localId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  channelId?: Prisma.StringFieldUpdateOperationsInput | string
  messsageId?: Prisma.StringFieldUpdateOperationsInput | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  options?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  minValues?: Prisma.IntFieldUpdateOperationsInput | number
  maxValues?: Prisma.IntFieldUpdateOperationsInput | number
  allowChangingVote?: Prisma.BoolFieldUpdateOperationsInput | boolean
  showResults?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type PollCountOutputType
 */

export type PollCountOutputType = {
  votes: number
}

export type PollCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  votes?: boolean | PollCountOutputTypeCountVotesArgs
}

/**
 * PollCountOutputType without action
 */
export type PollCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PollCountOutputType
   */
  select?: Prisma.PollCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PollCountOutputType without action
 */
export type PollCountOutputTypeCountVotesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VoteWhereInput
}


export type PollSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  localId?: boolean
  name?: boolean
  channelId?: boolean
  messsageId?: boolean
  active?: boolean
  options?: boolean
  minValues?: boolean
  maxValues?: boolean
  allowChangingVote?: boolean
  showResults?: boolean
  votes?: boolean | Prisma.Poll$votesArgs<ExtArgs>
  _count?: boolean | Prisma.PollCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["poll"]>

export type PollSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  localId?: boolean
  name?: boolean
  channelId?: boolean
  messsageId?: boolean
  active?: boolean
  options?: boolean
  minValues?: boolean
  maxValues?: boolean
  allowChangingVote?: boolean
  showResults?: boolean
}, ExtArgs["result"]["poll"]>

export type PollSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  localId?: boolean
  name?: boolean
  channelId?: boolean
  messsageId?: boolean
  active?: boolean
  options?: boolean
  minValues?: boolean
  maxValues?: boolean
  allowChangingVote?: boolean
  showResults?: boolean
}, ExtArgs["result"]["poll"]>

export type PollSelectScalar = {
  id?: boolean
  guildId?: boolean
  localId?: boolean
  name?: boolean
  channelId?: boolean
  messsageId?: boolean
  active?: boolean
  options?: boolean
  minValues?: boolean
  maxValues?: boolean
  allowChangingVote?: boolean
  showResults?: boolean
}

export type PollOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "guildId" | "localId" | "name" | "channelId" | "messsageId" | "active" | "options" | "minValues" | "maxValues" | "allowChangingVote" | "showResults", ExtArgs["result"]["poll"]>
export type PollInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  votes?: boolean | Prisma.Poll$votesArgs<ExtArgs>
  _count?: boolean | Prisma.PollCountOutputTypeDefaultArgs<ExtArgs>
}
export type PollIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PollIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PollPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Poll"
  objects: {
    votes: Prisma.$VotePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    guildId: string
    localId: string
    name: string
    channelId: string
    messsageId: string
    active: boolean
    options: runtime.JsonValue
    minValues: number
    maxValues: number
    allowChangingVote: boolean
    showResults: boolean
  }, ExtArgs["result"]["poll"]>
  composites: {}
}

export type PollGetPayload<S extends boolean | null | undefined | PollDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PollPayload, S>

export type PollCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PollFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PollCountAggregateInputType | true
  }

export interface PollDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Poll'], meta: { name: 'Poll' } }
  /**
   * Find zero or one Poll that matches the filter.
   * @param {PollFindUniqueArgs} args - Arguments to find a Poll
   * @example
   * // Get one Poll
   * const poll = await prisma.poll.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PollFindUniqueArgs>(args: Prisma.SelectSubset<T, PollFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PollClient<runtime.Types.Result.GetResult<Prisma.$PollPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Poll that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PollFindUniqueOrThrowArgs} args - Arguments to find a Poll
   * @example
   * // Get one Poll
   * const poll = await prisma.poll.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PollFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PollFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PollClient<runtime.Types.Result.GetResult<Prisma.$PollPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Poll that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PollFindFirstArgs} args - Arguments to find a Poll
   * @example
   * // Get one Poll
   * const poll = await prisma.poll.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PollFindFirstArgs>(args?: Prisma.SelectSubset<T, PollFindFirstArgs<ExtArgs>>): Prisma.Prisma__PollClient<runtime.Types.Result.GetResult<Prisma.$PollPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Poll that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PollFindFirstOrThrowArgs} args - Arguments to find a Poll
   * @example
   * // Get one Poll
   * const poll = await prisma.poll.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PollFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PollFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PollClient<runtime.Types.Result.GetResult<Prisma.$PollPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Polls that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PollFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Polls
   * const polls = await prisma.poll.findMany()
   * 
   * // Get first 10 Polls
   * const polls = await prisma.poll.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pollWithIdOnly = await prisma.poll.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PollFindManyArgs>(args?: Prisma.SelectSubset<T, PollFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PollPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Poll.
   * @param {PollCreateArgs} args - Arguments to create a Poll.
   * @example
   * // Create one Poll
   * const Poll = await prisma.poll.create({
   *   data: {
   *     // ... data to create a Poll
   *   }
   * })
   * 
   */
  create<T extends PollCreateArgs>(args: Prisma.SelectSubset<T, PollCreateArgs<ExtArgs>>): Prisma.Prisma__PollClient<runtime.Types.Result.GetResult<Prisma.$PollPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Polls.
   * @param {PollCreateManyArgs} args - Arguments to create many Polls.
   * @example
   * // Create many Polls
   * const poll = await prisma.poll.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PollCreateManyArgs>(args?: Prisma.SelectSubset<T, PollCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Polls and returns the data saved in the database.
   * @param {PollCreateManyAndReturnArgs} args - Arguments to create many Polls.
   * @example
   * // Create many Polls
   * const poll = await prisma.poll.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Polls and only return the `id`
   * const pollWithIdOnly = await prisma.poll.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PollCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PollCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PollPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Poll.
   * @param {PollDeleteArgs} args - Arguments to delete one Poll.
   * @example
   * // Delete one Poll
   * const Poll = await prisma.poll.delete({
   *   where: {
   *     // ... filter to delete one Poll
   *   }
   * })
   * 
   */
  delete<T extends PollDeleteArgs>(args: Prisma.SelectSubset<T, PollDeleteArgs<ExtArgs>>): Prisma.Prisma__PollClient<runtime.Types.Result.GetResult<Prisma.$PollPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Poll.
   * @param {PollUpdateArgs} args - Arguments to update one Poll.
   * @example
   * // Update one Poll
   * const poll = await prisma.poll.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PollUpdateArgs>(args: Prisma.SelectSubset<T, PollUpdateArgs<ExtArgs>>): Prisma.Prisma__PollClient<runtime.Types.Result.GetResult<Prisma.$PollPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Polls.
   * @param {PollDeleteManyArgs} args - Arguments to filter Polls to delete.
   * @example
   * // Delete a few Polls
   * const { count } = await prisma.poll.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PollDeleteManyArgs>(args?: Prisma.SelectSubset<T, PollDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Polls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PollUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Polls
   * const poll = await prisma.poll.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PollUpdateManyArgs>(args: Prisma.SelectSubset<T, PollUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Polls and returns the data updated in the database.
   * @param {PollUpdateManyAndReturnArgs} args - Arguments to update many Polls.
   * @example
   * // Update many Polls
   * const poll = await prisma.poll.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Polls and only return the `id`
   * const pollWithIdOnly = await prisma.poll.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PollUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PollUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PollPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Poll.
   * @param {PollUpsertArgs} args - Arguments to update or create a Poll.
   * @example
   * // Update or create a Poll
   * const poll = await prisma.poll.upsert({
   *   create: {
   *     // ... data to create a Poll
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Poll we want to update
   *   }
   * })
   */
  upsert<T extends PollUpsertArgs>(args: Prisma.SelectSubset<T, PollUpsertArgs<ExtArgs>>): Prisma.Prisma__PollClient<runtime.Types.Result.GetResult<Prisma.$PollPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Polls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PollCountArgs} args - Arguments to filter Polls to count.
   * @example
   * // Count the number of Polls
   * const count = await prisma.poll.count({
   *   where: {
   *     // ... the filter for the Polls we want to count
   *   }
   * })
  **/
  count<T extends PollCountArgs>(
    args?: Prisma.Subset<T, PollCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PollCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Poll.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PollAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PollAggregateArgs>(args: Prisma.Subset<T, PollAggregateArgs>): Prisma.PrismaPromise<GetPollAggregateType<T>>

  /**
   * Group by Poll.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PollGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PollGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PollGroupByArgs['orderBy'] }
      : { orderBy?: PollGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PollGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPollGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Poll model
 */
readonly fields: PollFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Poll.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PollClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  votes<T extends Prisma.Poll$votesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Poll$votesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Poll model
 */
export interface PollFieldRefs {
  readonly id: Prisma.FieldRef<"Poll", 'Int'>
  readonly guildId: Prisma.FieldRef<"Poll", 'String'>
  readonly localId: Prisma.FieldRef<"Poll", 'String'>
  readonly name: Prisma.FieldRef<"Poll", 'String'>
  readonly channelId: Prisma.FieldRef<"Poll", 'String'>
  readonly messsageId: Prisma.FieldRef<"Poll", 'String'>
  readonly active: Prisma.FieldRef<"Poll", 'Boolean'>
  readonly options: Prisma.FieldRef<"Poll", 'Json'>
  readonly minValues: Prisma.FieldRef<"Poll", 'Int'>
  readonly maxValues: Prisma.FieldRef<"Poll", 'Int'>
  readonly allowChangingVote: Prisma.FieldRef<"Poll", 'Boolean'>
  readonly showResults: Prisma.FieldRef<"Poll", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Poll findUnique
 */
export type PollFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Poll
   */
  select?: Prisma.PollSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Poll
   */
  omit?: Prisma.PollOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PollInclude<ExtArgs> | null
  /**
   * Filter, which Poll to fetch.
   */
  where: Prisma.PollWhereUniqueInput
}

/**
 * Poll findUniqueOrThrow
 */
export type PollFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Poll
   */
  select?: Prisma.PollSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Poll
   */
  omit?: Prisma.PollOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PollInclude<ExtArgs> | null
  /**
   * Filter, which Poll to fetch.
   */
  where: Prisma.PollWhereUniqueInput
}

/**
 * Poll findFirst
 */
export type PollFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Poll
   */
  select?: Prisma.PollSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Poll
   */
  omit?: Prisma.PollOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PollInclude<ExtArgs> | null
  /**
   * Filter, which Poll to fetch.
   */
  where?: Prisma.PollWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Polls to fetch.
   */
  orderBy?: Prisma.PollOrderByWithRelationInput | Prisma.PollOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Polls.
   */
  cursor?: Prisma.PollWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Polls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Polls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Polls.
   */
  distinct?: Prisma.PollScalarFieldEnum | Prisma.PollScalarFieldEnum[]
}

/**
 * Poll findFirstOrThrow
 */
export type PollFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Poll
   */
  select?: Prisma.PollSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Poll
   */
  omit?: Prisma.PollOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PollInclude<ExtArgs> | null
  /**
   * Filter, which Poll to fetch.
   */
  where?: Prisma.PollWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Polls to fetch.
   */
  orderBy?: Prisma.PollOrderByWithRelationInput | Prisma.PollOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Polls.
   */
  cursor?: Prisma.PollWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Polls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Polls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Polls.
   */
  distinct?: Prisma.PollScalarFieldEnum | Prisma.PollScalarFieldEnum[]
}

/**
 * Poll findMany
 */
export type PollFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Poll
   */
  select?: Prisma.PollSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Poll
   */
  omit?: Prisma.PollOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PollInclude<ExtArgs> | null
  /**
   * Filter, which Polls to fetch.
   */
  where?: Prisma.PollWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Polls to fetch.
   */
  orderBy?: Prisma.PollOrderByWithRelationInput | Prisma.PollOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Polls.
   */
  cursor?: Prisma.PollWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Polls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Polls.
   */
  skip?: number
  distinct?: Prisma.PollScalarFieldEnum | Prisma.PollScalarFieldEnum[]
}

/**
 * Poll create
 */
export type PollCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Poll
   */
  select?: Prisma.PollSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Poll
   */
  omit?: Prisma.PollOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PollInclude<ExtArgs> | null
  /**
   * The data needed to create a Poll.
   */
  data: Prisma.XOR<Prisma.PollCreateInput, Prisma.PollUncheckedCreateInput>
}

/**
 * Poll createMany
 */
export type PollCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Polls.
   */
  data: Prisma.PollCreateManyInput | Prisma.PollCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Poll createManyAndReturn
 */
export type PollCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Poll
   */
  select?: Prisma.PollSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Poll
   */
  omit?: Prisma.PollOmit<ExtArgs> | null
  /**
   * The data used to create many Polls.
   */
  data: Prisma.PollCreateManyInput | Prisma.PollCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Poll update
 */
export type PollUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Poll
   */
  select?: Prisma.PollSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Poll
   */
  omit?: Prisma.PollOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PollInclude<ExtArgs> | null
  /**
   * The data needed to update a Poll.
   */
  data: Prisma.XOR<Prisma.PollUpdateInput, Prisma.PollUncheckedUpdateInput>
  /**
   * Choose, which Poll to update.
   */
  where: Prisma.PollWhereUniqueInput
}

/**
 * Poll updateMany
 */
export type PollUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Polls.
   */
  data: Prisma.XOR<Prisma.PollUpdateManyMutationInput, Prisma.PollUncheckedUpdateManyInput>
  /**
   * Filter which Polls to update
   */
  where?: Prisma.PollWhereInput
  /**
   * Limit how many Polls to update.
   */
  limit?: number
}

/**
 * Poll updateManyAndReturn
 */
export type PollUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Poll
   */
  select?: Prisma.PollSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Poll
   */
  omit?: Prisma.PollOmit<ExtArgs> | null
  /**
   * The data used to update Polls.
   */
  data: Prisma.XOR<Prisma.PollUpdateManyMutationInput, Prisma.PollUncheckedUpdateManyInput>
  /**
   * Filter which Polls to update
   */
  where?: Prisma.PollWhereInput
  /**
   * Limit how many Polls to update.
   */
  limit?: number
}

/**
 * Poll upsert
 */
export type PollUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Poll
   */
  select?: Prisma.PollSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Poll
   */
  omit?: Prisma.PollOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PollInclude<ExtArgs> | null
  /**
   * The filter to search for the Poll to update in case it exists.
   */
  where: Prisma.PollWhereUniqueInput
  /**
   * In case the Poll found by the `where` argument doesn't exist, create a new Poll with this data.
   */
  create: Prisma.XOR<Prisma.PollCreateInput, Prisma.PollUncheckedCreateInput>
  /**
   * In case the Poll was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PollUpdateInput, Prisma.PollUncheckedUpdateInput>
}

/**
 * Poll delete
 */
export type PollDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Poll
   */
  select?: Prisma.PollSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Poll
   */
  omit?: Prisma.PollOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PollInclude<ExtArgs> | null
  /**
   * Filter which Poll to delete.
   */
  where: Prisma.PollWhereUniqueInput
}

/**
 * Poll deleteMany
 */
export type PollDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Polls to delete
   */
  where?: Prisma.PollWhereInput
  /**
   * Limit how many Polls to delete.
   */
  limit?: number
}

/**
 * Poll.votes
 */
export type Poll$votesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Vote
   */
  select?: Prisma.VoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Vote
   */
  omit?: Prisma.VoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VoteInclude<ExtArgs> | null
  where?: Prisma.VoteWhereInput
  orderBy?: Prisma.VoteOrderByWithRelationInput | Prisma.VoteOrderByWithRelationInput[]
  cursor?: Prisma.VoteWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VoteScalarFieldEnum | Prisma.VoteScalarFieldEnum[]
}

/**
 * Poll without action
 */
export type PollDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Poll
   */
  select?: Prisma.PollSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Poll
   */
  omit?: Prisma.PollOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PollInclude<ExtArgs> | null
}
