
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Quote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Quote
 * 
 */
export type QuoteModel = runtime.Types.Result.DefaultSelection<Prisma.$QuotePayload>

export type AggregateQuote = {
  _count: QuoteCountAggregateOutputType | null
  _avg: QuoteAvgAggregateOutputType | null
  _sum: QuoteSumAggregateOutputType | null
  _min: QuoteMinAggregateOutputType | null
  _max: QuoteMaxAggregateOutputType | null
}

export type QuoteAvgAggregateOutputType = {
  id: number | null
}

export type QuoteSumAggregateOutputType = {
  id: number | null
}

export type QuoteMinAggregateOutputType = {
  id: number | null
  guildId: string | null
  userId: string | null
  messageId: string | null
}

export type QuoteMaxAggregateOutputType = {
  id: number | null
  guildId: string | null
  userId: string | null
  messageId: string | null
}

export type QuoteCountAggregateOutputType = {
  id: number
  guildId: number
  userId: number
  messageId: number
  message: number
  _all: number
}


export type QuoteAvgAggregateInputType = {
  id?: true
}

export type QuoteSumAggregateInputType = {
  id?: true
}

export type QuoteMinAggregateInputType = {
  id?: true
  guildId?: true
  userId?: true
  messageId?: true
}

export type QuoteMaxAggregateInputType = {
  id?: true
  guildId?: true
  userId?: true
  messageId?: true
}

export type QuoteCountAggregateInputType = {
  id?: true
  guildId?: true
  userId?: true
  messageId?: true
  message?: true
  _all?: true
}

export type QuoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Quote to aggregate.
   */
  where?: Prisma.QuoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Quotes to fetch.
   */
  orderBy?: Prisma.QuoteOrderByWithRelationInput | Prisma.QuoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Quotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Quotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Quotes
  **/
  _count?: true | QuoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: QuoteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: QuoteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuoteMaxAggregateInputType
}

export type GetQuoteAggregateType<T extends QuoteAggregateArgs> = {
      [P in keyof T & keyof AggregateQuote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuote[P]>
    : Prisma.GetScalarType<T[P], AggregateQuote[P]>
}




export type QuoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuoteWhereInput
  orderBy?: Prisma.QuoteOrderByWithAggregationInput | Prisma.QuoteOrderByWithAggregationInput[]
  by: Prisma.QuoteScalarFieldEnum[] | Prisma.QuoteScalarFieldEnum
  having?: Prisma.QuoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuoteCountAggregateInputType | true
  _avg?: QuoteAvgAggregateInputType
  _sum?: QuoteSumAggregateInputType
  _min?: QuoteMinAggregateInputType
  _max?: QuoteMaxAggregateInputType
}

export type QuoteGroupByOutputType = {
  id: number
  guildId: string
  userId: string
  messageId: string | null
  message: runtime.JsonValue
  _count: QuoteCountAggregateOutputType | null
  _avg: QuoteAvgAggregateOutputType | null
  _sum: QuoteSumAggregateOutputType | null
  _min: QuoteMinAggregateOutputType | null
  _max: QuoteMaxAggregateOutputType | null
}

type GetQuoteGroupByPayload<T extends QuoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuoteGroupByOutputType[P]>
      }
    >
  >



export type QuoteWhereInput = {
  AND?: Prisma.QuoteWhereInput | Prisma.QuoteWhereInput[]
  OR?: Prisma.QuoteWhereInput[]
  NOT?: Prisma.QuoteWhereInput | Prisma.QuoteWhereInput[]
  id?: Prisma.IntFilter<"Quote"> | number
  guildId?: Prisma.StringFilter<"Quote"> | string
  userId?: Prisma.StringFilter<"Quote"> | string
  messageId?: Prisma.StringNullableFilter<"Quote"> | string | null
  message?: Prisma.JsonFilter<"Quote">
}

export type QuoteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  messageId?: Prisma.SortOrderInput | Prisma.SortOrder
  message?: Prisma.SortOrder
}

export type QuoteWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  messageId?: string
  AND?: Prisma.QuoteWhereInput | Prisma.QuoteWhereInput[]
  OR?: Prisma.QuoteWhereInput[]
  NOT?: Prisma.QuoteWhereInput | Prisma.QuoteWhereInput[]
  guildId?: Prisma.StringFilter<"Quote"> | string
  userId?: Prisma.StringFilter<"Quote"> | string
  message?: Prisma.JsonFilter<"Quote">
}, "id" | "messageId">

export type QuoteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  messageId?: Prisma.SortOrderInput | Prisma.SortOrder
  message?: Prisma.SortOrder
  _count?: Prisma.QuoteCountOrderByAggregateInput
  _avg?: Prisma.QuoteAvgOrderByAggregateInput
  _max?: Prisma.QuoteMaxOrderByAggregateInput
  _min?: Prisma.QuoteMinOrderByAggregateInput
  _sum?: Prisma.QuoteSumOrderByAggregateInput
}

export type QuoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuoteScalarWhereWithAggregatesInput | Prisma.QuoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuoteScalarWhereWithAggregatesInput | Prisma.QuoteScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Quote"> | number
  guildId?: Prisma.StringWithAggregatesFilter<"Quote"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Quote"> | string
  messageId?: Prisma.StringNullableWithAggregatesFilter<"Quote"> | string | null
  message?: Prisma.JsonWithAggregatesFilter<"Quote">
}

export type QuoteCreateInput = {
  guildId: string
  userId: string
  messageId?: string | null
  message: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type QuoteUncheckedCreateInput = {
  id?: number
  guildId: string
  userId: string
  messageId?: string | null
  message: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type QuoteUpdateInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type QuoteUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type QuoteCreateManyInput = {
  id?: number
  guildId: string
  userId: string
  messageId?: string | null
  message: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type QuoteUpdateManyMutationInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type QuoteUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type QuoteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  message?: Prisma.SortOrder
}

export type QuoteAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type QuoteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
}

export type QuoteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
}

export type QuoteSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type QuoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  userId?: boolean
  messageId?: boolean
  message?: boolean
}, ExtArgs["result"]["quote"]>

export type QuoteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  userId?: boolean
  messageId?: boolean
  message?: boolean
}, ExtArgs["result"]["quote"]>

export type QuoteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  userId?: boolean
  messageId?: boolean
  message?: boolean
}, ExtArgs["result"]["quote"]>

export type QuoteSelectScalar = {
  id?: boolean
  guildId?: boolean
  userId?: boolean
  messageId?: boolean
  message?: boolean
}

export type QuoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "guildId" | "userId" | "messageId" | "message", ExtArgs["result"]["quote"]>

export type $QuotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Quote"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    guildId: string
    userId: string
    messageId: string | null
    message: runtime.JsonValue
  }, ExtArgs["result"]["quote"]>
  composites: {}
}

export type QuoteGetPayload<S extends boolean | null | undefined | QuoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuotePayload, S>

export type QuoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuoteCountAggregateInputType | true
  }

export interface QuoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Quote'], meta: { name: 'Quote' } }
  /**
   * Find zero or one Quote that matches the filter.
   * @param {QuoteFindUniqueArgs} args - Arguments to find a Quote
   * @example
   * // Get one Quote
   * const quote = await prisma.quote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuoteFindUniqueArgs>(args: Prisma.SelectSubset<T, QuoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuoteClient<runtime.Types.Result.GetResult<Prisma.$QuotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Quote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuoteFindUniqueOrThrowArgs} args - Arguments to find a Quote
   * @example
   * // Get one Quote
   * const quote = await prisma.quote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuoteClient<runtime.Types.Result.GetResult<Prisma.$QuotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Quote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteFindFirstArgs} args - Arguments to find a Quote
   * @example
   * // Get one Quote
   * const quote = await prisma.quote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuoteFindFirstArgs>(args?: Prisma.SelectSubset<T, QuoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuoteClient<runtime.Types.Result.GetResult<Prisma.$QuotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Quote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteFindFirstOrThrowArgs} args - Arguments to find a Quote
   * @example
   * // Get one Quote
   * const quote = await prisma.quote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuoteClient<runtime.Types.Result.GetResult<Prisma.$QuotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Quotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Quotes
   * const quotes = await prisma.quote.findMany()
   * 
   * // Get first 10 Quotes
   * const quotes = await prisma.quote.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const quoteWithIdOnly = await prisma.quote.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuoteFindManyArgs>(args?: Prisma.SelectSubset<T, QuoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Quote.
   * @param {QuoteCreateArgs} args - Arguments to create a Quote.
   * @example
   * // Create one Quote
   * const Quote = await prisma.quote.create({
   *   data: {
   *     // ... data to create a Quote
   *   }
   * })
   * 
   */
  create<T extends QuoteCreateArgs>(args: Prisma.SelectSubset<T, QuoteCreateArgs<ExtArgs>>): Prisma.Prisma__QuoteClient<runtime.Types.Result.GetResult<Prisma.$QuotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Quotes.
   * @param {QuoteCreateManyArgs} args - Arguments to create many Quotes.
   * @example
   * // Create many Quotes
   * const quote = await prisma.quote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuoteCreateManyArgs>(args?: Prisma.SelectSubset<T, QuoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Quotes and returns the data saved in the database.
   * @param {QuoteCreateManyAndReturnArgs} args - Arguments to create many Quotes.
   * @example
   * // Create many Quotes
   * const quote = await prisma.quote.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Quotes and only return the `id`
   * const quoteWithIdOnly = await prisma.quote.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuoteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuoteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuotePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Quote.
   * @param {QuoteDeleteArgs} args - Arguments to delete one Quote.
   * @example
   * // Delete one Quote
   * const Quote = await prisma.quote.delete({
   *   where: {
   *     // ... filter to delete one Quote
   *   }
   * })
   * 
   */
  delete<T extends QuoteDeleteArgs>(args: Prisma.SelectSubset<T, QuoteDeleteArgs<ExtArgs>>): Prisma.Prisma__QuoteClient<runtime.Types.Result.GetResult<Prisma.$QuotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Quote.
   * @param {QuoteUpdateArgs} args - Arguments to update one Quote.
   * @example
   * // Update one Quote
   * const quote = await prisma.quote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuoteUpdateArgs>(args: Prisma.SelectSubset<T, QuoteUpdateArgs<ExtArgs>>): Prisma.Prisma__QuoteClient<runtime.Types.Result.GetResult<Prisma.$QuotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Quotes.
   * @param {QuoteDeleteManyArgs} args - Arguments to filter Quotes to delete.
   * @example
   * // Delete a few Quotes
   * const { count } = await prisma.quote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Quotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Quotes
   * const quote = await prisma.quote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuoteUpdateManyArgs>(args: Prisma.SelectSubset<T, QuoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Quotes and returns the data updated in the database.
   * @param {QuoteUpdateManyAndReturnArgs} args - Arguments to update many Quotes.
   * @example
   * // Update many Quotes
   * const quote = await prisma.quote.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Quotes and only return the `id`
   * const quoteWithIdOnly = await prisma.quote.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuoteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuoteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuotePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Quote.
   * @param {QuoteUpsertArgs} args - Arguments to update or create a Quote.
   * @example
   * // Update or create a Quote
   * const quote = await prisma.quote.upsert({
   *   create: {
   *     // ... data to create a Quote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Quote we want to update
   *   }
   * })
   */
  upsert<T extends QuoteUpsertArgs>(args: Prisma.SelectSubset<T, QuoteUpsertArgs<ExtArgs>>): Prisma.Prisma__QuoteClient<runtime.Types.Result.GetResult<Prisma.$QuotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Quotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteCountArgs} args - Arguments to filter Quotes to count.
   * @example
   * // Count the number of Quotes
   * const count = await prisma.quote.count({
   *   where: {
   *     // ... the filter for the Quotes we want to count
   *   }
   * })
  **/
  count<T extends QuoteCountArgs>(
    args?: Prisma.Subset<T, QuoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Quote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuoteAggregateArgs>(args: Prisma.Subset<T, QuoteAggregateArgs>): Prisma.PrismaPromise<GetQuoteAggregateType<T>>

  /**
   * Group by Quote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuoteGroupByArgs['orderBy'] }
      : { orderBy?: QuoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Quote model
 */
readonly fields: QuoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Quote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Quote model
 */
export interface QuoteFieldRefs {
  readonly id: Prisma.FieldRef<"Quote", 'Int'>
  readonly guildId: Prisma.FieldRef<"Quote", 'String'>
  readonly userId: Prisma.FieldRef<"Quote", 'String'>
  readonly messageId: Prisma.FieldRef<"Quote", 'String'>
  readonly message: Prisma.FieldRef<"Quote", 'Json'>
}
    

// Custom InputTypes
/**
 * Quote findUnique
 */
export type QuoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quote
   */
  select?: Prisma.QuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Quote
   */
  omit?: Prisma.QuoteOmit<ExtArgs> | null
  /**
   * Filter, which Quote to fetch.
   */
  where: Prisma.QuoteWhereUniqueInput
}

/**
 * Quote findUniqueOrThrow
 */
export type QuoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quote
   */
  select?: Prisma.QuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Quote
   */
  omit?: Prisma.QuoteOmit<ExtArgs> | null
  /**
   * Filter, which Quote to fetch.
   */
  where: Prisma.QuoteWhereUniqueInput
}

/**
 * Quote findFirst
 */
export type QuoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quote
   */
  select?: Prisma.QuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Quote
   */
  omit?: Prisma.QuoteOmit<ExtArgs> | null
  /**
   * Filter, which Quote to fetch.
   */
  where?: Prisma.QuoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Quotes to fetch.
   */
  orderBy?: Prisma.QuoteOrderByWithRelationInput | Prisma.QuoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Quotes.
   */
  cursor?: Prisma.QuoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Quotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Quotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Quotes.
   */
  distinct?: Prisma.QuoteScalarFieldEnum | Prisma.QuoteScalarFieldEnum[]
}

/**
 * Quote findFirstOrThrow
 */
export type QuoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quote
   */
  select?: Prisma.QuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Quote
   */
  omit?: Prisma.QuoteOmit<ExtArgs> | null
  /**
   * Filter, which Quote to fetch.
   */
  where?: Prisma.QuoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Quotes to fetch.
   */
  orderBy?: Prisma.QuoteOrderByWithRelationInput | Prisma.QuoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Quotes.
   */
  cursor?: Prisma.QuoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Quotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Quotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Quotes.
   */
  distinct?: Prisma.QuoteScalarFieldEnum | Prisma.QuoteScalarFieldEnum[]
}

/**
 * Quote findMany
 */
export type QuoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quote
   */
  select?: Prisma.QuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Quote
   */
  omit?: Prisma.QuoteOmit<ExtArgs> | null
  /**
   * Filter, which Quotes to fetch.
   */
  where?: Prisma.QuoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Quotes to fetch.
   */
  orderBy?: Prisma.QuoteOrderByWithRelationInput | Prisma.QuoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Quotes.
   */
  cursor?: Prisma.QuoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Quotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Quotes.
   */
  skip?: number
  distinct?: Prisma.QuoteScalarFieldEnum | Prisma.QuoteScalarFieldEnum[]
}

/**
 * Quote create
 */
export type QuoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quote
   */
  select?: Prisma.QuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Quote
   */
  omit?: Prisma.QuoteOmit<ExtArgs> | null
  /**
   * The data needed to create a Quote.
   */
  data: Prisma.XOR<Prisma.QuoteCreateInput, Prisma.QuoteUncheckedCreateInput>
}

/**
 * Quote createMany
 */
export type QuoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Quotes.
   */
  data: Prisma.QuoteCreateManyInput | Prisma.QuoteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Quote createManyAndReturn
 */
export type QuoteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quote
   */
  select?: Prisma.QuoteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Quote
   */
  omit?: Prisma.QuoteOmit<ExtArgs> | null
  /**
   * The data used to create many Quotes.
   */
  data: Prisma.QuoteCreateManyInput | Prisma.QuoteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Quote update
 */
export type QuoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quote
   */
  select?: Prisma.QuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Quote
   */
  omit?: Prisma.QuoteOmit<ExtArgs> | null
  /**
   * The data needed to update a Quote.
   */
  data: Prisma.XOR<Prisma.QuoteUpdateInput, Prisma.QuoteUncheckedUpdateInput>
  /**
   * Choose, which Quote to update.
   */
  where: Prisma.QuoteWhereUniqueInput
}

/**
 * Quote updateMany
 */
export type QuoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Quotes.
   */
  data: Prisma.XOR<Prisma.QuoteUpdateManyMutationInput, Prisma.QuoteUncheckedUpdateManyInput>
  /**
   * Filter which Quotes to update
   */
  where?: Prisma.QuoteWhereInput
  /**
   * Limit how many Quotes to update.
   */
  limit?: number
}

/**
 * Quote updateManyAndReturn
 */
export type QuoteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quote
   */
  select?: Prisma.QuoteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Quote
   */
  omit?: Prisma.QuoteOmit<ExtArgs> | null
  /**
   * The data used to update Quotes.
   */
  data: Prisma.XOR<Prisma.QuoteUpdateManyMutationInput, Prisma.QuoteUncheckedUpdateManyInput>
  /**
   * Filter which Quotes to update
   */
  where?: Prisma.QuoteWhereInput
  /**
   * Limit how many Quotes to update.
   */
  limit?: number
}

/**
 * Quote upsert
 */
export type QuoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quote
   */
  select?: Prisma.QuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Quote
   */
  omit?: Prisma.QuoteOmit<ExtArgs> | null
  /**
   * The filter to search for the Quote to update in case it exists.
   */
  where: Prisma.QuoteWhereUniqueInput
  /**
   * In case the Quote found by the `where` argument doesn't exist, create a new Quote with this data.
   */
  create: Prisma.XOR<Prisma.QuoteCreateInput, Prisma.QuoteUncheckedCreateInput>
  /**
   * In case the Quote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuoteUpdateInput, Prisma.QuoteUncheckedUpdateInput>
}

/**
 * Quote delete
 */
export type QuoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quote
   */
  select?: Prisma.QuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Quote
   */
  omit?: Prisma.QuoteOmit<ExtArgs> | null
  /**
   * Filter which Quote to delete.
   */
  where: Prisma.QuoteWhereUniqueInput
}

/**
 * Quote deleteMany
 */
export type QuoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Quotes to delete
   */
  where?: Prisma.QuoteWhereInput
  /**
   * Limit how many Quotes to delete.
   */
  limit?: number
}

/**
 * Quote without action
 */
export type QuoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Quote
   */
  select?: Prisma.QuoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Quote
   */
  omit?: Prisma.QuoteOmit<ExtArgs> | null
}
