
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `StarboardItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model StarboardItem
 * 
 */
export type StarboardItemModel = runtime.Types.Result.DefaultSelection<Prisma.$StarboardItemPayload>

export type AggregateStarboardItem = {
  _count: StarboardItemCountAggregateOutputType | null
  _avg: StarboardItemAvgAggregateOutputType | null
  _sum: StarboardItemSumAggregateOutputType | null
  _min: StarboardItemMinAggregateOutputType | null
  _max: StarboardItemMaxAggregateOutputType | null
}

export type StarboardItemAvgAggregateOutputType = {
  id: number | null
}

export type StarboardItemSumAggregateOutputType = {
  id: number | null
}

export type StarboardItemMinAggregateOutputType = {
  id: number | null
  guildId: string | null
  messageId: string | null
  starboardMessageId: string | null
}

export type StarboardItemMaxAggregateOutputType = {
  id: number | null
  guildId: string | null
  messageId: string | null
  starboardMessageId: string | null
}

export type StarboardItemCountAggregateOutputType = {
  id: number
  guildId: number
  messageId: number
  starboardMessageId: number
  _all: number
}


export type StarboardItemAvgAggregateInputType = {
  id?: true
}

export type StarboardItemSumAggregateInputType = {
  id?: true
}

export type StarboardItemMinAggregateInputType = {
  id?: true
  guildId?: true
  messageId?: true
  starboardMessageId?: true
}

export type StarboardItemMaxAggregateInputType = {
  id?: true
  guildId?: true
  messageId?: true
  starboardMessageId?: true
}

export type StarboardItemCountAggregateInputType = {
  id?: true
  guildId?: true
  messageId?: true
  starboardMessageId?: true
  _all?: true
}

export type StarboardItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StarboardItem to aggregate.
   */
  where?: Prisma.StarboardItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StarboardItems to fetch.
   */
  orderBy?: Prisma.StarboardItemOrderByWithRelationInput | Prisma.StarboardItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StarboardItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StarboardItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StarboardItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StarboardItems
  **/
  _count?: true | StarboardItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StarboardItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StarboardItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StarboardItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StarboardItemMaxAggregateInputType
}

export type GetStarboardItemAggregateType<T extends StarboardItemAggregateArgs> = {
      [P in keyof T & keyof AggregateStarboardItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStarboardItem[P]>
    : Prisma.GetScalarType<T[P], AggregateStarboardItem[P]>
}




export type StarboardItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StarboardItemWhereInput
  orderBy?: Prisma.StarboardItemOrderByWithAggregationInput | Prisma.StarboardItemOrderByWithAggregationInput[]
  by: Prisma.StarboardItemScalarFieldEnum[] | Prisma.StarboardItemScalarFieldEnum
  having?: Prisma.StarboardItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StarboardItemCountAggregateInputType | true
  _avg?: StarboardItemAvgAggregateInputType
  _sum?: StarboardItemSumAggregateInputType
  _min?: StarboardItemMinAggregateInputType
  _max?: StarboardItemMaxAggregateInputType
}

export type StarboardItemGroupByOutputType = {
  id: number
  guildId: string
  messageId: string
  starboardMessageId: string
  _count: StarboardItemCountAggregateOutputType | null
  _avg: StarboardItemAvgAggregateOutputType | null
  _sum: StarboardItemSumAggregateOutputType | null
  _min: StarboardItemMinAggregateOutputType | null
  _max: StarboardItemMaxAggregateOutputType | null
}

type GetStarboardItemGroupByPayload<T extends StarboardItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StarboardItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StarboardItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StarboardItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StarboardItemGroupByOutputType[P]>
      }
    >
  >



export type StarboardItemWhereInput = {
  AND?: Prisma.StarboardItemWhereInput | Prisma.StarboardItemWhereInput[]
  OR?: Prisma.StarboardItemWhereInput[]
  NOT?: Prisma.StarboardItemWhereInput | Prisma.StarboardItemWhereInput[]
  id?: Prisma.IntFilter<"StarboardItem"> | number
  guildId?: Prisma.StringFilter<"StarboardItem"> | string
  messageId?: Prisma.StringFilter<"StarboardItem"> | string
  starboardMessageId?: Prisma.StringFilter<"StarboardItem"> | string
}

export type StarboardItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  starboardMessageId?: Prisma.SortOrder
}

export type StarboardItemWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  messageId?: string
  AND?: Prisma.StarboardItemWhereInput | Prisma.StarboardItemWhereInput[]
  OR?: Prisma.StarboardItemWhereInput[]
  NOT?: Prisma.StarboardItemWhereInput | Prisma.StarboardItemWhereInput[]
  guildId?: Prisma.StringFilter<"StarboardItem"> | string
  starboardMessageId?: Prisma.StringFilter<"StarboardItem"> | string
}, "id" | "messageId">

export type StarboardItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  starboardMessageId?: Prisma.SortOrder
  _count?: Prisma.StarboardItemCountOrderByAggregateInput
  _avg?: Prisma.StarboardItemAvgOrderByAggregateInput
  _max?: Prisma.StarboardItemMaxOrderByAggregateInput
  _min?: Prisma.StarboardItemMinOrderByAggregateInput
  _sum?: Prisma.StarboardItemSumOrderByAggregateInput
}

export type StarboardItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.StarboardItemScalarWhereWithAggregatesInput | Prisma.StarboardItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.StarboardItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StarboardItemScalarWhereWithAggregatesInput | Prisma.StarboardItemScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"StarboardItem"> | number
  guildId?: Prisma.StringWithAggregatesFilter<"StarboardItem"> | string
  messageId?: Prisma.StringWithAggregatesFilter<"StarboardItem"> | string
  starboardMessageId?: Prisma.StringWithAggregatesFilter<"StarboardItem"> | string
}

export type StarboardItemCreateInput = {
  guildId: string
  messageId: string
  starboardMessageId: string
}

export type StarboardItemUncheckedCreateInput = {
  id?: number
  guildId: string
  messageId: string
  starboardMessageId: string
}

export type StarboardItemUpdateInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  starboardMessageId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StarboardItemUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  starboardMessageId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StarboardItemCreateManyInput = {
  id?: number
  guildId: string
  messageId: string
  starboardMessageId: string
}

export type StarboardItemUpdateManyMutationInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  starboardMessageId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StarboardItemUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  starboardMessageId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StarboardItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  starboardMessageId?: Prisma.SortOrder
}

export type StarboardItemAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StarboardItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  starboardMessageId?: Prisma.SortOrder
}

export type StarboardItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  starboardMessageId?: Prisma.SortOrder
}

export type StarboardItemSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type StarboardItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  messageId?: boolean
  starboardMessageId?: boolean
}, ExtArgs["result"]["starboardItem"]>

export type StarboardItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  messageId?: boolean
  starboardMessageId?: boolean
}, ExtArgs["result"]["starboardItem"]>

export type StarboardItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  messageId?: boolean
  starboardMessageId?: boolean
}, ExtArgs["result"]["starboardItem"]>

export type StarboardItemSelectScalar = {
  id?: boolean
  guildId?: boolean
  messageId?: boolean
  starboardMessageId?: boolean
}

export type StarboardItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "guildId" | "messageId" | "starboardMessageId", ExtArgs["result"]["starboardItem"]>

export type $StarboardItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StarboardItem"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    guildId: string
    messageId: string
    starboardMessageId: string
  }, ExtArgs["result"]["starboardItem"]>
  composites: {}
}

export type StarboardItemGetPayload<S extends boolean | null | undefined | StarboardItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StarboardItemPayload, S>

export type StarboardItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StarboardItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StarboardItemCountAggregateInputType | true
  }

export interface StarboardItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StarboardItem'], meta: { name: 'StarboardItem' } }
  /**
   * Find zero or one StarboardItem that matches the filter.
   * @param {StarboardItemFindUniqueArgs} args - Arguments to find a StarboardItem
   * @example
   * // Get one StarboardItem
   * const starboardItem = await prisma.starboardItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StarboardItemFindUniqueArgs>(args: Prisma.SelectSubset<T, StarboardItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StarboardItemClient<runtime.Types.Result.GetResult<Prisma.$StarboardItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StarboardItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StarboardItemFindUniqueOrThrowArgs} args - Arguments to find a StarboardItem
   * @example
   * // Get one StarboardItem
   * const starboardItem = await prisma.starboardItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StarboardItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StarboardItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StarboardItemClient<runtime.Types.Result.GetResult<Prisma.$StarboardItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StarboardItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StarboardItemFindFirstArgs} args - Arguments to find a StarboardItem
   * @example
   * // Get one StarboardItem
   * const starboardItem = await prisma.starboardItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StarboardItemFindFirstArgs>(args?: Prisma.SelectSubset<T, StarboardItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__StarboardItemClient<runtime.Types.Result.GetResult<Prisma.$StarboardItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StarboardItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StarboardItemFindFirstOrThrowArgs} args - Arguments to find a StarboardItem
   * @example
   * // Get one StarboardItem
   * const starboardItem = await prisma.starboardItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StarboardItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StarboardItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StarboardItemClient<runtime.Types.Result.GetResult<Prisma.$StarboardItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StarboardItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StarboardItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StarboardItems
   * const starboardItems = await prisma.starboardItem.findMany()
   * 
   * // Get first 10 StarboardItems
   * const starboardItems = await prisma.starboardItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const starboardItemWithIdOnly = await prisma.starboardItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StarboardItemFindManyArgs>(args?: Prisma.SelectSubset<T, StarboardItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StarboardItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StarboardItem.
   * @param {StarboardItemCreateArgs} args - Arguments to create a StarboardItem.
   * @example
   * // Create one StarboardItem
   * const StarboardItem = await prisma.starboardItem.create({
   *   data: {
   *     // ... data to create a StarboardItem
   *   }
   * })
   * 
   */
  create<T extends StarboardItemCreateArgs>(args: Prisma.SelectSubset<T, StarboardItemCreateArgs<ExtArgs>>): Prisma.Prisma__StarboardItemClient<runtime.Types.Result.GetResult<Prisma.$StarboardItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StarboardItems.
   * @param {StarboardItemCreateManyArgs} args - Arguments to create many StarboardItems.
   * @example
   * // Create many StarboardItems
   * const starboardItem = await prisma.starboardItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StarboardItemCreateManyArgs>(args?: Prisma.SelectSubset<T, StarboardItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StarboardItems and returns the data saved in the database.
   * @param {StarboardItemCreateManyAndReturnArgs} args - Arguments to create many StarboardItems.
   * @example
   * // Create many StarboardItems
   * const starboardItem = await prisma.starboardItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StarboardItems and only return the `id`
   * const starboardItemWithIdOnly = await prisma.starboardItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StarboardItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StarboardItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StarboardItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StarboardItem.
   * @param {StarboardItemDeleteArgs} args - Arguments to delete one StarboardItem.
   * @example
   * // Delete one StarboardItem
   * const StarboardItem = await prisma.starboardItem.delete({
   *   where: {
   *     // ... filter to delete one StarboardItem
   *   }
   * })
   * 
   */
  delete<T extends StarboardItemDeleteArgs>(args: Prisma.SelectSubset<T, StarboardItemDeleteArgs<ExtArgs>>): Prisma.Prisma__StarboardItemClient<runtime.Types.Result.GetResult<Prisma.$StarboardItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StarboardItem.
   * @param {StarboardItemUpdateArgs} args - Arguments to update one StarboardItem.
   * @example
   * // Update one StarboardItem
   * const starboardItem = await prisma.starboardItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StarboardItemUpdateArgs>(args: Prisma.SelectSubset<T, StarboardItemUpdateArgs<ExtArgs>>): Prisma.Prisma__StarboardItemClient<runtime.Types.Result.GetResult<Prisma.$StarboardItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StarboardItems.
   * @param {StarboardItemDeleteManyArgs} args - Arguments to filter StarboardItems to delete.
   * @example
   * // Delete a few StarboardItems
   * const { count } = await prisma.starboardItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StarboardItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, StarboardItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StarboardItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StarboardItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StarboardItems
   * const starboardItem = await prisma.starboardItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StarboardItemUpdateManyArgs>(args: Prisma.SelectSubset<T, StarboardItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StarboardItems and returns the data updated in the database.
   * @param {StarboardItemUpdateManyAndReturnArgs} args - Arguments to update many StarboardItems.
   * @example
   * // Update many StarboardItems
   * const starboardItem = await prisma.starboardItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StarboardItems and only return the `id`
   * const starboardItemWithIdOnly = await prisma.starboardItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StarboardItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StarboardItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StarboardItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StarboardItem.
   * @param {StarboardItemUpsertArgs} args - Arguments to update or create a StarboardItem.
   * @example
   * // Update or create a StarboardItem
   * const starboardItem = await prisma.starboardItem.upsert({
   *   create: {
   *     // ... data to create a StarboardItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StarboardItem we want to update
   *   }
   * })
   */
  upsert<T extends StarboardItemUpsertArgs>(args: Prisma.SelectSubset<T, StarboardItemUpsertArgs<ExtArgs>>): Prisma.Prisma__StarboardItemClient<runtime.Types.Result.GetResult<Prisma.$StarboardItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StarboardItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StarboardItemCountArgs} args - Arguments to filter StarboardItems to count.
   * @example
   * // Count the number of StarboardItems
   * const count = await prisma.starboardItem.count({
   *   where: {
   *     // ... the filter for the StarboardItems we want to count
   *   }
   * })
  **/
  count<T extends StarboardItemCountArgs>(
    args?: Prisma.Subset<T, StarboardItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StarboardItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StarboardItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StarboardItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StarboardItemAggregateArgs>(args: Prisma.Subset<T, StarboardItemAggregateArgs>): Prisma.PrismaPromise<GetStarboardItemAggregateType<T>>

  /**
   * Group by StarboardItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StarboardItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StarboardItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StarboardItemGroupByArgs['orderBy'] }
      : { orderBy?: StarboardItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StarboardItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStarboardItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StarboardItem model
 */
readonly fields: StarboardItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StarboardItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StarboardItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StarboardItem model
 */
export interface StarboardItemFieldRefs {
  readonly id: Prisma.FieldRef<"StarboardItem", 'Int'>
  readonly guildId: Prisma.FieldRef<"StarboardItem", 'String'>
  readonly messageId: Prisma.FieldRef<"StarboardItem", 'String'>
  readonly starboardMessageId: Prisma.FieldRef<"StarboardItem", 'String'>
}
    

// Custom InputTypes
/**
 * StarboardItem findUnique
 */
export type StarboardItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StarboardItem
   */
  select?: Prisma.StarboardItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StarboardItem
   */
  omit?: Prisma.StarboardItemOmit<ExtArgs> | null
  /**
   * Filter, which StarboardItem to fetch.
   */
  where: Prisma.StarboardItemWhereUniqueInput
}

/**
 * StarboardItem findUniqueOrThrow
 */
export type StarboardItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StarboardItem
   */
  select?: Prisma.StarboardItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StarboardItem
   */
  omit?: Prisma.StarboardItemOmit<ExtArgs> | null
  /**
   * Filter, which StarboardItem to fetch.
   */
  where: Prisma.StarboardItemWhereUniqueInput
}

/**
 * StarboardItem findFirst
 */
export type StarboardItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StarboardItem
   */
  select?: Prisma.StarboardItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StarboardItem
   */
  omit?: Prisma.StarboardItemOmit<ExtArgs> | null
  /**
   * Filter, which StarboardItem to fetch.
   */
  where?: Prisma.StarboardItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StarboardItems to fetch.
   */
  orderBy?: Prisma.StarboardItemOrderByWithRelationInput | Prisma.StarboardItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StarboardItems.
   */
  cursor?: Prisma.StarboardItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StarboardItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StarboardItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StarboardItems.
   */
  distinct?: Prisma.StarboardItemScalarFieldEnum | Prisma.StarboardItemScalarFieldEnum[]
}

/**
 * StarboardItem findFirstOrThrow
 */
export type StarboardItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StarboardItem
   */
  select?: Prisma.StarboardItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StarboardItem
   */
  omit?: Prisma.StarboardItemOmit<ExtArgs> | null
  /**
   * Filter, which StarboardItem to fetch.
   */
  where?: Prisma.StarboardItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StarboardItems to fetch.
   */
  orderBy?: Prisma.StarboardItemOrderByWithRelationInput | Prisma.StarboardItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StarboardItems.
   */
  cursor?: Prisma.StarboardItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StarboardItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StarboardItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StarboardItems.
   */
  distinct?: Prisma.StarboardItemScalarFieldEnum | Prisma.StarboardItemScalarFieldEnum[]
}

/**
 * StarboardItem findMany
 */
export type StarboardItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StarboardItem
   */
  select?: Prisma.StarboardItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StarboardItem
   */
  omit?: Prisma.StarboardItemOmit<ExtArgs> | null
  /**
   * Filter, which StarboardItems to fetch.
   */
  where?: Prisma.StarboardItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StarboardItems to fetch.
   */
  orderBy?: Prisma.StarboardItemOrderByWithRelationInput | Prisma.StarboardItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StarboardItems.
   */
  cursor?: Prisma.StarboardItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StarboardItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StarboardItems.
   */
  skip?: number
  distinct?: Prisma.StarboardItemScalarFieldEnum | Prisma.StarboardItemScalarFieldEnum[]
}

/**
 * StarboardItem create
 */
export type StarboardItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StarboardItem
   */
  select?: Prisma.StarboardItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StarboardItem
   */
  omit?: Prisma.StarboardItemOmit<ExtArgs> | null
  /**
   * The data needed to create a StarboardItem.
   */
  data: Prisma.XOR<Prisma.StarboardItemCreateInput, Prisma.StarboardItemUncheckedCreateInput>
}

/**
 * StarboardItem createMany
 */
export type StarboardItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StarboardItems.
   */
  data: Prisma.StarboardItemCreateManyInput | Prisma.StarboardItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StarboardItem createManyAndReturn
 */
export type StarboardItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StarboardItem
   */
  select?: Prisma.StarboardItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StarboardItem
   */
  omit?: Prisma.StarboardItemOmit<ExtArgs> | null
  /**
   * The data used to create many StarboardItems.
   */
  data: Prisma.StarboardItemCreateManyInput | Prisma.StarboardItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StarboardItem update
 */
export type StarboardItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StarboardItem
   */
  select?: Prisma.StarboardItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StarboardItem
   */
  omit?: Prisma.StarboardItemOmit<ExtArgs> | null
  /**
   * The data needed to update a StarboardItem.
   */
  data: Prisma.XOR<Prisma.StarboardItemUpdateInput, Prisma.StarboardItemUncheckedUpdateInput>
  /**
   * Choose, which StarboardItem to update.
   */
  where: Prisma.StarboardItemWhereUniqueInput
}

/**
 * StarboardItem updateMany
 */
export type StarboardItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StarboardItems.
   */
  data: Prisma.XOR<Prisma.StarboardItemUpdateManyMutationInput, Prisma.StarboardItemUncheckedUpdateManyInput>
  /**
   * Filter which StarboardItems to update
   */
  where?: Prisma.StarboardItemWhereInput
  /**
   * Limit how many StarboardItems to update.
   */
  limit?: number
}

/**
 * StarboardItem updateManyAndReturn
 */
export type StarboardItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StarboardItem
   */
  select?: Prisma.StarboardItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StarboardItem
   */
  omit?: Prisma.StarboardItemOmit<ExtArgs> | null
  /**
   * The data used to update StarboardItems.
   */
  data: Prisma.XOR<Prisma.StarboardItemUpdateManyMutationInput, Prisma.StarboardItemUncheckedUpdateManyInput>
  /**
   * Filter which StarboardItems to update
   */
  where?: Prisma.StarboardItemWhereInput
  /**
   * Limit how many StarboardItems to update.
   */
  limit?: number
}

/**
 * StarboardItem upsert
 */
export type StarboardItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StarboardItem
   */
  select?: Prisma.StarboardItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StarboardItem
   */
  omit?: Prisma.StarboardItemOmit<ExtArgs> | null
  /**
   * The filter to search for the StarboardItem to update in case it exists.
   */
  where: Prisma.StarboardItemWhereUniqueInput
  /**
   * In case the StarboardItem found by the `where` argument doesn't exist, create a new StarboardItem with this data.
   */
  create: Prisma.XOR<Prisma.StarboardItemCreateInput, Prisma.StarboardItemUncheckedCreateInput>
  /**
   * In case the StarboardItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StarboardItemUpdateInput, Prisma.StarboardItemUncheckedUpdateInput>
}

/**
 * StarboardItem delete
 */
export type StarboardItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StarboardItem
   */
  select?: Prisma.StarboardItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StarboardItem
   */
  omit?: Prisma.StarboardItemOmit<ExtArgs> | null
  /**
   * Filter which StarboardItem to delete.
   */
  where: Prisma.StarboardItemWhereUniqueInput
}

/**
 * StarboardItem deleteMany
 */
export type StarboardItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StarboardItems to delete
   */
  where?: Prisma.StarboardItemWhereInput
  /**
   * Limit how many StarboardItems to delete.
   */
  limit?: number
}

/**
 * StarboardItem without action
 */
export type StarboardItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StarboardItem
   */
  select?: Prisma.StarboardItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StarboardItem
   */
  omit?: Prisma.StarboardItemOmit<ExtArgs> | null
}
