
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Sticker` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Sticker
 * 
 */
export type StickerModel = runtime.Types.Result.DefaultSelection<Prisma.$StickerPayload>

export type AggregateSticker = {
  _count: StickerCountAggregateOutputType | null
  _avg: StickerAvgAggregateOutputType | null
  _sum: StickerSumAggregateOutputType | null
  _min: StickerMinAggregateOutputType | null
  _max: StickerMaxAggregateOutputType | null
}

export type StickerAvgAggregateOutputType = {
  id: number | null
}

export type StickerSumAggregateOutputType = {
  id: number | null
}

export type StickerMinAggregateOutputType = {
  id: number | null
  guildId: string | null
  tag: string | null
  url: string | null
}

export type StickerMaxAggregateOutputType = {
  id: number | null
  guildId: string | null
  tag: string | null
  url: string | null
}

export type StickerCountAggregateOutputType = {
  id: number
  guildId: number
  tag: number
  url: number
  _all: number
}


export type StickerAvgAggregateInputType = {
  id?: true
}

export type StickerSumAggregateInputType = {
  id?: true
}

export type StickerMinAggregateInputType = {
  id?: true
  guildId?: true
  tag?: true
  url?: true
}

export type StickerMaxAggregateInputType = {
  id?: true
  guildId?: true
  tag?: true
  url?: true
}

export type StickerCountAggregateInputType = {
  id?: true
  guildId?: true
  tag?: true
  url?: true
  _all?: true
}

export type StickerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Sticker to aggregate.
   */
  where?: Prisma.StickerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stickers to fetch.
   */
  orderBy?: Prisma.StickerOrderByWithRelationInput | Prisma.StickerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StickerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stickers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stickers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Stickers
  **/
  _count?: true | StickerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StickerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StickerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StickerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StickerMaxAggregateInputType
}

export type GetStickerAggregateType<T extends StickerAggregateArgs> = {
      [P in keyof T & keyof AggregateSticker]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSticker[P]>
    : Prisma.GetScalarType<T[P], AggregateSticker[P]>
}




export type StickerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StickerWhereInput
  orderBy?: Prisma.StickerOrderByWithAggregationInput | Prisma.StickerOrderByWithAggregationInput[]
  by: Prisma.StickerScalarFieldEnum[] | Prisma.StickerScalarFieldEnum
  having?: Prisma.StickerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StickerCountAggregateInputType | true
  _avg?: StickerAvgAggregateInputType
  _sum?: StickerSumAggregateInputType
  _min?: StickerMinAggregateInputType
  _max?: StickerMaxAggregateInputType
}

export type StickerGroupByOutputType = {
  id: number
  guildId: string
  tag: string
  url: string
  _count: StickerCountAggregateOutputType | null
  _avg: StickerAvgAggregateOutputType | null
  _sum: StickerSumAggregateOutputType | null
  _min: StickerMinAggregateOutputType | null
  _max: StickerMaxAggregateOutputType | null
}

type GetStickerGroupByPayload<T extends StickerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StickerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StickerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StickerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StickerGroupByOutputType[P]>
      }
    >
  >



export type StickerWhereInput = {
  AND?: Prisma.StickerWhereInput | Prisma.StickerWhereInput[]
  OR?: Prisma.StickerWhereInput[]
  NOT?: Prisma.StickerWhereInput | Prisma.StickerWhereInput[]
  id?: Prisma.IntFilter<"Sticker"> | number
  guildId?: Prisma.StringFilter<"Sticker"> | string
  tag?: Prisma.StringFilter<"Sticker"> | string
  url?: Prisma.StringFilter<"Sticker"> | string
}

export type StickerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  url?: Prisma.SortOrder
}

export type StickerWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  guildId_tag?: Prisma.StickerGuildIdTagCompoundUniqueInput
  AND?: Prisma.StickerWhereInput | Prisma.StickerWhereInput[]
  OR?: Prisma.StickerWhereInput[]
  NOT?: Prisma.StickerWhereInput | Prisma.StickerWhereInput[]
  guildId?: Prisma.StringFilter<"Sticker"> | string
  tag?: Prisma.StringFilter<"Sticker"> | string
  url?: Prisma.StringFilter<"Sticker"> | string
}, "id" | "guildId_tag">

export type StickerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  url?: Prisma.SortOrder
  _count?: Prisma.StickerCountOrderByAggregateInput
  _avg?: Prisma.StickerAvgOrderByAggregateInput
  _max?: Prisma.StickerMaxOrderByAggregateInput
  _min?: Prisma.StickerMinOrderByAggregateInput
  _sum?: Prisma.StickerSumOrderByAggregateInput
}

export type StickerScalarWhereWithAggregatesInput = {
  AND?: Prisma.StickerScalarWhereWithAggregatesInput | Prisma.StickerScalarWhereWithAggregatesInput[]
  OR?: Prisma.StickerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StickerScalarWhereWithAggregatesInput | Prisma.StickerScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Sticker"> | number
  guildId?: Prisma.StringWithAggregatesFilter<"Sticker"> | string
  tag?: Prisma.StringWithAggregatesFilter<"Sticker"> | string
  url?: Prisma.StringWithAggregatesFilter<"Sticker"> | string
}

export type StickerCreateInput = {
  guildId: string
  tag: string
  url: string
}

export type StickerUncheckedCreateInput = {
  id?: number
  guildId: string
  tag: string
  url: string
}

export type StickerUpdateInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StickerUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StickerCreateManyInput = {
  id?: number
  guildId: string
  tag: string
  url: string
}

export type StickerUpdateManyMutationInput = {
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StickerUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StickerGuildIdTagCompoundUniqueInput = {
  guildId: string
  tag: string
}

export type StickerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  url?: Prisma.SortOrder
}

export type StickerAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StickerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  url?: Prisma.SortOrder
}

export type StickerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  url?: Prisma.SortOrder
}

export type StickerSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type StickerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  tag?: boolean
  url?: boolean
}, ExtArgs["result"]["sticker"]>

export type StickerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  tag?: boolean
  url?: boolean
}, ExtArgs["result"]["sticker"]>

export type StickerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guildId?: boolean
  tag?: boolean
  url?: boolean
}, ExtArgs["result"]["sticker"]>

export type StickerSelectScalar = {
  id?: boolean
  guildId?: boolean
  tag?: boolean
  url?: boolean
}

export type StickerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "guildId" | "tag" | "url", ExtArgs["result"]["sticker"]>

export type $StickerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Sticker"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    guildId: string
    tag: string
    url: string
  }, ExtArgs["result"]["sticker"]>
  composites: {}
}

export type StickerGetPayload<S extends boolean | null | undefined | StickerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StickerPayload, S>

export type StickerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StickerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StickerCountAggregateInputType | true
  }

export interface StickerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Sticker'], meta: { name: 'Sticker' } }
  /**
   * Find zero or one Sticker that matches the filter.
   * @param {StickerFindUniqueArgs} args - Arguments to find a Sticker
   * @example
   * // Get one Sticker
   * const sticker = await prisma.sticker.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StickerFindUniqueArgs>(args: Prisma.SelectSubset<T, StickerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StickerClient<runtime.Types.Result.GetResult<Prisma.$StickerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Sticker that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StickerFindUniqueOrThrowArgs} args - Arguments to find a Sticker
   * @example
   * // Get one Sticker
   * const sticker = await prisma.sticker.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StickerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StickerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StickerClient<runtime.Types.Result.GetResult<Prisma.$StickerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Sticker that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StickerFindFirstArgs} args - Arguments to find a Sticker
   * @example
   * // Get one Sticker
   * const sticker = await prisma.sticker.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StickerFindFirstArgs>(args?: Prisma.SelectSubset<T, StickerFindFirstArgs<ExtArgs>>): Prisma.Prisma__StickerClient<runtime.Types.Result.GetResult<Prisma.$StickerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Sticker that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StickerFindFirstOrThrowArgs} args - Arguments to find a Sticker
   * @example
   * // Get one Sticker
   * const sticker = await prisma.sticker.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StickerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StickerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StickerClient<runtime.Types.Result.GetResult<Prisma.$StickerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Stickers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StickerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Stickers
   * const stickers = await prisma.sticker.findMany()
   * 
   * // Get first 10 Stickers
   * const stickers = await prisma.sticker.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const stickerWithIdOnly = await prisma.sticker.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StickerFindManyArgs>(args?: Prisma.SelectSubset<T, StickerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StickerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Sticker.
   * @param {StickerCreateArgs} args - Arguments to create a Sticker.
   * @example
   * // Create one Sticker
   * const Sticker = await prisma.sticker.create({
   *   data: {
   *     // ... data to create a Sticker
   *   }
   * })
   * 
   */
  create<T extends StickerCreateArgs>(args: Prisma.SelectSubset<T, StickerCreateArgs<ExtArgs>>): Prisma.Prisma__StickerClient<runtime.Types.Result.GetResult<Prisma.$StickerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Stickers.
   * @param {StickerCreateManyArgs} args - Arguments to create many Stickers.
   * @example
   * // Create many Stickers
   * const sticker = await prisma.sticker.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StickerCreateManyArgs>(args?: Prisma.SelectSubset<T, StickerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Stickers and returns the data saved in the database.
   * @param {StickerCreateManyAndReturnArgs} args - Arguments to create many Stickers.
   * @example
   * // Create many Stickers
   * const sticker = await prisma.sticker.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Stickers and only return the `id`
   * const stickerWithIdOnly = await prisma.sticker.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StickerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StickerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StickerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Sticker.
   * @param {StickerDeleteArgs} args - Arguments to delete one Sticker.
   * @example
   * // Delete one Sticker
   * const Sticker = await prisma.sticker.delete({
   *   where: {
   *     // ... filter to delete one Sticker
   *   }
   * })
   * 
   */
  delete<T extends StickerDeleteArgs>(args: Prisma.SelectSubset<T, StickerDeleteArgs<ExtArgs>>): Prisma.Prisma__StickerClient<runtime.Types.Result.GetResult<Prisma.$StickerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Sticker.
   * @param {StickerUpdateArgs} args - Arguments to update one Sticker.
   * @example
   * // Update one Sticker
   * const sticker = await prisma.sticker.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StickerUpdateArgs>(args: Prisma.SelectSubset<T, StickerUpdateArgs<ExtArgs>>): Prisma.Prisma__StickerClient<runtime.Types.Result.GetResult<Prisma.$StickerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Stickers.
   * @param {StickerDeleteManyArgs} args - Arguments to filter Stickers to delete.
   * @example
   * // Delete a few Stickers
   * const { count } = await prisma.sticker.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StickerDeleteManyArgs>(args?: Prisma.SelectSubset<T, StickerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Stickers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StickerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Stickers
   * const sticker = await prisma.sticker.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StickerUpdateManyArgs>(args: Prisma.SelectSubset<T, StickerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Stickers and returns the data updated in the database.
   * @param {StickerUpdateManyAndReturnArgs} args - Arguments to update many Stickers.
   * @example
   * // Update many Stickers
   * const sticker = await prisma.sticker.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Stickers and only return the `id`
   * const stickerWithIdOnly = await prisma.sticker.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StickerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StickerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StickerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Sticker.
   * @param {StickerUpsertArgs} args - Arguments to update or create a Sticker.
   * @example
   * // Update or create a Sticker
   * const sticker = await prisma.sticker.upsert({
   *   create: {
   *     // ... data to create a Sticker
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Sticker we want to update
   *   }
   * })
   */
  upsert<T extends StickerUpsertArgs>(args: Prisma.SelectSubset<T, StickerUpsertArgs<ExtArgs>>): Prisma.Prisma__StickerClient<runtime.Types.Result.GetResult<Prisma.$StickerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Stickers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StickerCountArgs} args - Arguments to filter Stickers to count.
   * @example
   * // Count the number of Stickers
   * const count = await prisma.sticker.count({
   *   where: {
   *     // ... the filter for the Stickers we want to count
   *   }
   * })
  **/
  count<T extends StickerCountArgs>(
    args?: Prisma.Subset<T, StickerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StickerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Sticker.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StickerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StickerAggregateArgs>(args: Prisma.Subset<T, StickerAggregateArgs>): Prisma.PrismaPromise<GetStickerAggregateType<T>>

  /**
   * Group by Sticker.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StickerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StickerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StickerGroupByArgs['orderBy'] }
      : { orderBy?: StickerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StickerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStickerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Sticker model
 */
readonly fields: StickerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Sticker.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StickerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Sticker model
 */
export interface StickerFieldRefs {
  readonly id: Prisma.FieldRef<"Sticker", 'Int'>
  readonly guildId: Prisma.FieldRef<"Sticker", 'String'>
  readonly tag: Prisma.FieldRef<"Sticker", 'String'>
  readonly url: Prisma.FieldRef<"Sticker", 'String'>
}
    

// Custom InputTypes
/**
 * Sticker findUnique
 */
export type StickerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sticker
   */
  select?: Prisma.StickerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sticker
   */
  omit?: Prisma.StickerOmit<ExtArgs> | null
  /**
   * Filter, which Sticker to fetch.
   */
  where: Prisma.StickerWhereUniqueInput
}

/**
 * Sticker findUniqueOrThrow
 */
export type StickerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sticker
   */
  select?: Prisma.StickerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sticker
   */
  omit?: Prisma.StickerOmit<ExtArgs> | null
  /**
   * Filter, which Sticker to fetch.
   */
  where: Prisma.StickerWhereUniqueInput
}

/**
 * Sticker findFirst
 */
export type StickerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sticker
   */
  select?: Prisma.StickerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sticker
   */
  omit?: Prisma.StickerOmit<ExtArgs> | null
  /**
   * Filter, which Sticker to fetch.
   */
  where?: Prisma.StickerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stickers to fetch.
   */
  orderBy?: Prisma.StickerOrderByWithRelationInput | Prisma.StickerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Stickers.
   */
  cursor?: Prisma.StickerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stickers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stickers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Stickers.
   */
  distinct?: Prisma.StickerScalarFieldEnum | Prisma.StickerScalarFieldEnum[]
}

/**
 * Sticker findFirstOrThrow
 */
export type StickerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sticker
   */
  select?: Prisma.StickerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sticker
   */
  omit?: Prisma.StickerOmit<ExtArgs> | null
  /**
   * Filter, which Sticker to fetch.
   */
  where?: Prisma.StickerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stickers to fetch.
   */
  orderBy?: Prisma.StickerOrderByWithRelationInput | Prisma.StickerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Stickers.
   */
  cursor?: Prisma.StickerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stickers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stickers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Stickers.
   */
  distinct?: Prisma.StickerScalarFieldEnum | Prisma.StickerScalarFieldEnum[]
}

/**
 * Sticker findMany
 */
export type StickerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sticker
   */
  select?: Prisma.StickerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sticker
   */
  omit?: Prisma.StickerOmit<ExtArgs> | null
  /**
   * Filter, which Stickers to fetch.
   */
  where?: Prisma.StickerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stickers to fetch.
   */
  orderBy?: Prisma.StickerOrderByWithRelationInput | Prisma.StickerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Stickers.
   */
  cursor?: Prisma.StickerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stickers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stickers.
   */
  skip?: number
  distinct?: Prisma.StickerScalarFieldEnum | Prisma.StickerScalarFieldEnum[]
}

/**
 * Sticker create
 */
export type StickerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sticker
   */
  select?: Prisma.StickerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sticker
   */
  omit?: Prisma.StickerOmit<ExtArgs> | null
  /**
   * The data needed to create a Sticker.
   */
  data: Prisma.XOR<Prisma.StickerCreateInput, Prisma.StickerUncheckedCreateInput>
}

/**
 * Sticker createMany
 */
export type StickerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Stickers.
   */
  data: Prisma.StickerCreateManyInput | Prisma.StickerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Sticker createManyAndReturn
 */
export type StickerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sticker
   */
  select?: Prisma.StickerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Sticker
   */
  omit?: Prisma.StickerOmit<ExtArgs> | null
  /**
   * The data used to create many Stickers.
   */
  data: Prisma.StickerCreateManyInput | Prisma.StickerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Sticker update
 */
export type StickerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sticker
   */
  select?: Prisma.StickerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sticker
   */
  omit?: Prisma.StickerOmit<ExtArgs> | null
  /**
   * The data needed to update a Sticker.
   */
  data: Prisma.XOR<Prisma.StickerUpdateInput, Prisma.StickerUncheckedUpdateInput>
  /**
   * Choose, which Sticker to update.
   */
  where: Prisma.StickerWhereUniqueInput
}

/**
 * Sticker updateMany
 */
export type StickerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Stickers.
   */
  data: Prisma.XOR<Prisma.StickerUpdateManyMutationInput, Prisma.StickerUncheckedUpdateManyInput>
  /**
   * Filter which Stickers to update
   */
  where?: Prisma.StickerWhereInput
  /**
   * Limit how many Stickers to update.
   */
  limit?: number
}

/**
 * Sticker updateManyAndReturn
 */
export type StickerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sticker
   */
  select?: Prisma.StickerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Sticker
   */
  omit?: Prisma.StickerOmit<ExtArgs> | null
  /**
   * The data used to update Stickers.
   */
  data: Prisma.XOR<Prisma.StickerUpdateManyMutationInput, Prisma.StickerUncheckedUpdateManyInput>
  /**
   * Filter which Stickers to update
   */
  where?: Prisma.StickerWhereInput
  /**
   * Limit how many Stickers to update.
   */
  limit?: number
}

/**
 * Sticker upsert
 */
export type StickerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sticker
   */
  select?: Prisma.StickerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sticker
   */
  omit?: Prisma.StickerOmit<ExtArgs> | null
  /**
   * The filter to search for the Sticker to update in case it exists.
   */
  where: Prisma.StickerWhereUniqueInput
  /**
   * In case the Sticker found by the `where` argument doesn't exist, create a new Sticker with this data.
   */
  create: Prisma.XOR<Prisma.StickerCreateInput, Prisma.StickerUncheckedCreateInput>
  /**
   * In case the Sticker was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StickerUpdateInput, Prisma.StickerUncheckedUpdateInput>
}

/**
 * Sticker delete
 */
export type StickerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sticker
   */
  select?: Prisma.StickerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sticker
   */
  omit?: Prisma.StickerOmit<ExtArgs> | null
  /**
   * Filter which Sticker to delete.
   */
  where: Prisma.StickerWhereUniqueInput
}

/**
 * Sticker deleteMany
 */
export type StickerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Stickers to delete
   */
  where?: Prisma.StickerWhereInput
  /**
   * Limit how many Stickers to delete.
   */
  limit?: number
}

/**
 * Sticker without action
 */
export type StickerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sticker
   */
  select?: Prisma.StickerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sticker
   */
  omit?: Prisma.StickerOmit<ExtArgs> | null
}
