name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          push: true
          tags: omegavesko/shinoa:${{ github.sha }}

      - name: Build and push Docker image (tags latest)
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          push: true
          tags: omegavesko/shinoa:${{ github.sha }},omegavesko/shinoa:latest

      - name: Deploy to production
        uses: digitalocean/app_action@v1.1.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          app_name: shinoa
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: |
            [
              {
                "name": "shinoa",
                "image": {
                  "registry_type": "DOCKER_HUB",
                  "registry": "omegavesko",
                  "repository": "shinoa",
                  "tag": "${{ github.sha }}"
                }
              }
            ]
